---
base_path: "/glade/work/rjarolim/nf2/spherical/2173_scaled_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/2173_scaled_v01"
logging:
  project: nf2-domain
  name: "spherical - 2173 - scaled"
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: synoptic
      batch_size: 8192
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
#    - type: pfss_boundary
#      ds_id: pfss_boundary
#      Br: "/glade/work/rjarolim/data/global/fd_2106/hmi.synoptic_mr_polfil_720s.2106.Mr_polfil.fits"
    - type: random_spherical
      ds_id: random
      batch_size: 16384
  validation_configs:
    - type: map
      ds_id: synoptic
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
  max_radius: 1.3
  G_per_dB: 2000
  num_workers: 8
  batch_size: 16384
  iterations: 10000
model:
  type: 'b_scaled'
  spherical: true
  encoding_config: {type: "gaussian"}
  dim: 256
training:
  epochs: 1000
  loss_config:
    - type: boundary
      name: boundary
      lambda: 10.0
      ds_id: [synoptic]
      height_scaling: True
#      asinh_scaling: True
#    - type: energy_gradient
#      name: energy_gradient
#      lambda: 1.0e-2 #1.0
#      ds_id: random
#      base_radius: 1.04
#      height_scaling: True
#    - type: potential
#      lambda: 1.0e-3
#      ds_id: random
#      base_radius: 1.04
    - type: force_free
      lambda: 1.0e-2
      height_scaling: True
    - type: divergence
      lambda: 1.0e-2
      height_scaling: True
    - type: b_height_scaling
      lambda: 1.0e-2
#    - type: radial
#      lambda: 1.0e-3
#      base_radius: 1.3