---
base_path: "/glade/work/rjarolim/nf2/spherical/2173/domain_vp_{time}_v05"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/domain_vp_{time}_v05"
logging:
  project: nf2-domain
  name: "spherical - 2173 VP - {time}"
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: synoptic
      batch_size: 4096
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
    - type: random_spherical
      ds_id: random_1
      batch_size: 16384
  validation_configs:
    - type: map
      ds_id: full_disk_valid
      filter_nans: false
      shuffle: false
      plot_overview: false
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bp_err.fits"
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
  max_radius: 1.3
  G_per_dB: 2000
  num_workers: 8
  batch_size: 16384
  iterations: 10000
model:
  type: 'b_scaled'
  spherical: true
  encoding_config: {type: "gaussian"}
  dim: 256
training:
  epochs: 1000
  loss_config:
    - type: boundary
      name: boundary
      lambda: 10.0
      ds_id: [synoptic]
#    - type: energy_gradient
#      name: energy_gradient
#      lambda: 1.0
#      ds_id: random_1
#      base_radius: 1.04
#      height_scaling: True
    - type: force_free
      lambda: 1.0e-2
      height_scaling: True
    - type: divergence
      lambda: 1.0e-1
      height_scaling: True