---
base_path: "/glade/work/rjarolim/nf2/spherical/2173_domain_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/2173_domain_v01"
logging:
  project: nf2-domain
  name: "spherical - 2173 - domain"
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: synoptic
      batch_size: 4096
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
    - type: random_spherical
      ds_id: random_1
      batch_size: 12288
      radius_range: [1.0, 1.03]
    - type: random_spherical
      ds_id: random_2
      batch_size: 4096
      radius_range: [1.03, 1.3]
  validation_configs:
    - type: map
      ds_id: synoptic
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
  max_radius: 1.3
  G_per_dB: 2000
  num_workers: 8
  batch_size: 16384
  iterations: 10000
model:
  type: 'multi_domain'
  overlap_width: 2.0
  range_config:
    - { model_type: 'b_scaled', start: null, end: 100.0 }
    - { model_type: 'potential', start: 100.0, end: null }
  spherical: true
  dim: 256
  encoding_config: {type: "gaussian"}
#  encoding_config: {type: "positional"}
training:
  epochs: 100
  loss_config:
    - type: boundary
      name: boundary
      lambda: 10.0
      ds_id: [synoptic]
      height_scaling: True
    - type: energy_gradient
      name: energy_gradient
      lambda: 1.0e-2 #1.0
      ds_id: [random_1, random_2]
      base_radius: 1.04
      height_scaling: True
    - type: force_free
      lambda: 1.0e-2
      height_scaling: True
    - type: divergence
      lambda: 1.0e-2
      height_scaling: True
    - type: b_height_scaling
      lambda: 1.0e-2