---
base_path: "/gpfs/gpfs0/robert.jarolim/nf2/topology/muram_mfr_2slices_v01"
work_directory: "/trinity/home/robert.jarolim/nf2/muram_mfr_2slices_v01"
logging:
  project: topology
  name: MURAM MFR - tau1 + tau1e-4
data:
  type: cartesian
  train_configs:
    - type: muram_slice
      ds_id: tau_1.0
      data_path: "/gpfs/gpfs0/robert.jarolim/data/nf2/muram_mfr/tau_slice_1.000.474000"
      los_trv_azi_transform: True
    - type: muram_slice
      ds_id: tau_1.0e-4
      data_path: "/gpfs/gpfs0/robert.jarolim/data/nf2/muram_mfr/tau_slice_0.000100.474000"
      height_mapping: { z: 0.6, z_min: 0, z_max: 5 }
      los_trv_azi_transform: True
  num_workers: 8
  iterations: 10000
  batch_size: 4096
  random_config:
    batch_size: 16384
  z_range: [ 0, 50 ]
  boundary_config:
    type: potential
    batch_size: 1024
model:
  type: gauged_vector_potential
  dim: 256
training:
  epochs: 10

loss:
  - type: boundary_los_trv_azi
    name: boundary
    lambda: 1.0
    ds_id: [ tau_1.0, tau_1.0e-4 ]
  - type: boundary
    name: potential_boundary
    lambda: 1.0e+1
    ds_id: potential
  - type: force_free
    lambda: 1.0e-2
  - type: height
    name: height
    lambda: 1.0e-4
    ds_id: [ tau_1.0e-4 ]

transforms:
  - type: height
    ds_id: [ tau_1.0e-4 ]

callbacks:
    # Boundary callbacks
  - type: los_trv_azi_boundary
    name: boundary-tau_1.0
    ds_id: tau_1.0
  - type: los_trv_azi_boundary
    name: boundary-tau_1.0e-4
    ds_id: tau_1.0e-4
  # Cube evaluation
  - type: metrics
    name: metrics-tau_1.0
    ds_id: cube
  - type: slices
    ds_id: slices