---
base_path: "/glade/work/rjarolim/nf2/spherical/2173/{time}_v06"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/{time}_v06"
logging:
  project: spherical
  name: "2173 {time}"
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: full_disk
      batch_size: 4096
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bp.fits"
#       Br_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Br_err.fits"
#       Bt_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bt_err.fits"
#       Bp_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bp_err.fits"
#      mask_configs:
#        type: heliographic_carrington
#        longitude_range: [ 1.446, 4.273 ]
#        latitude_range: [ 0.424, 2.938 ]
#        invert: true
    - type: map
      ds_id: synoptic
      batch_size: 4096
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
      mask_configs:
#        type: heliographic_carrington
#        longitude_range: [ 1.446, 4.273 ]
#        latitude_range: [ 0.424, 2.938 ]
        type: reference
        file: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Br.fits"
    - type: random_spherical
      ds_id: random
      batch_size: 16384
#      longitude_range: [ 1.446, 4.273 ]
#      latitude_range: [  0.424, 2.938 ]
  validation_configs:
    - type: map
      ds_id: full_disk_valid
      filter_nans: false
      shuffle: false
      plot_overview: false
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.{time}_TAI.Bp_err.fits"
      mask_configs:
        type: heliographic_carrington
        longitude_range: [ 1.446, 4.273 ]
        latitude_range: [ 0.424, 2.938 ]
        invert: true
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
      longitude_range: [ 1.446, 4.273 ]
      latitude_range: [  0.424, 2.938 ]
    - type: sphere
      ds_id: sphere
      longitude_range: [ 1.446, 4.273 ]
      latitude_range: [  0.424, 2.938 ]
  max_radius: 1.3
  G_per_dB: 2000
  num_workers: 8
  batch_size: 16384
  iterations: 10000
model:
  type: vector_potential
  dim: 512
training:
  epochs: 1000
  loss_config:
    - type: boundary
      name: boundary
      lambda: {start: 1.0e+3, end: 20.0, iterations: 5.0e+4}
      ds_id: [full_disk, synoptic]
    - type: energy_gradient
      lambda: 10.0
      ds_id: random
      base_radius: 1.04
    - type: potential
      lambda: 1.0e-2
      ds_id: random
      base_radius: 1.04
    - type: force_free
      lambda: 0.1