---
base_path: "/glade/work/rjarolim/nf2/spherical/2173_series_v03"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/2173_series_v03"
meta_path: "/glade/work/rjarolim/nf2/spherical/2173/20160205_160000_v03/last.ckpt"
logging:
  project: spherical
  name: "2173 series"
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: full_disk
      batch_size: 8192
      requires_jacobian: False
      files:
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_171200_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_171200_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_171200_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_172400_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_172400_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_172400_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_173600_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_173600_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_173600_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_174800_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_174800_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_174800_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_180000_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_180000_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_180000_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_181200_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_181200_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_181200_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_182400_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_182400_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_182400_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_183600_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_183600_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_183600_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_184800_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_184800_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_184800_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_190000_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_190000_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_190000_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_191200_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_191200_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_191200_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_192400_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_192400_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_192400_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_193600_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_193600_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_193600_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_194800_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_194800_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_194800_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_200000_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_200000_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_200000_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_201200_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_201200_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_201200_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_202400_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_202400_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_202400_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_203600_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_203600_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_203600_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_204800_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_204800_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_204800_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_210000_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_210000_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_210000_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_211200_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_211200_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_211200_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_212400_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_212400_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_212400_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_213600_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_213600_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_213600_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_214800_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_214800_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_214800_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_220000_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_220000_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_220000_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_221200_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_221200_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_221200_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_222400_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_222400_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_222400_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_223600_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_223600_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_223600_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_224800_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_224800_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_224800_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_230000_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_230000_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_230000_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_231200_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_231200_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_231200_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_232400_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_232400_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_232400_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_233600_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_233600_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_233600_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_234800_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_234800_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_234800_TAI.Bp.fits"
        - Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160206_000000_TAI.Br.fits"
          Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160206_000000_TAI.Bt.fits"
          Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160206_000000_TAI.Bp.fits"
    - type: map
      ds_id: synoptic
      batch_size: 4096
      requires_jacobian: False
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
      mask_configs:
        - type: reference
          file: "<<full_disk.files.Br>>"
    - type: random_radial_grouped
      ds_id: random
      batch_size: 16384
      n_lat_lon_sample: 64
      length: 1.0e+3
  validation_configs:
    - type: map
      ds_id: synoptic_valid
      filter_nans: false
      shuffle: false
      plot_overview: false
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
    - type: sphere
      ds_id: sphere
  max_radius: 1.5
  G_per_dB: 100
  num_workers: 16
  batch_size: 16384
  iterations: 2000
model:
  type: vector_potential
  dim: 256

loss:
  - type: boundary
    name: boundary
    lambda: 1.0
    ds_id: [full_disk, synoptic]
  - type: force_free
    name: force_free
    lambda: 1.0e-3
    ds_id: [ random ]
  - type: potential
    name: potential
    lambda: 0.0
    ds_id: [ random ]
  - type: potential
    name: potential_top
    lambda: 1.0e-3
    ds_id: [ random ]
  - type: energy_gradient
    name: energy_gradient
    lambda: 1.0e+1
    ds_id: [ random ]

loss_scaling:
  - type: b_height
    name: b_height
    loss_ids: [ force_free, potential, potential_top, energy_gradient ]
    power: 1.0
  - type: radial
    name: radial
    base_radius: 1.2
    loss_ids: [ energy_gradient, potential_top ]


callbacks:
  - type: boundary
    name: synoptic_boundary
    ds_id: synoptic_valid
    component_labels: [ r, t, p ]
  - type: metrics
    name: metrics
    ds_id: sphere
  - type: spherical_slices
    ds_id: slices
