---
base_path: "/glade/work/rjarolim/nf2/spherical/2173_subframe_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/2173_subframe_v01"
logging:
  project: spherical
  name: "2173 subframe"
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: AR
      batch_size: 4096
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bp_err.fits"
      mask_configs:
        type: heliographic_carrington
        longitude_range: [ 2.336, 3.384 ]
        latitude_range: [  1.157, 2.205 ]
        invert: true
    - type: random_spherical
      ds_id: random
      batch_size: 8192
      longitude_range: [ 2.336, 3.384 ]
      latitude_range: [  1.157, 2.205 ]
  validation_configs:
    - type: map
      ds_id: AR_valid
      filter_nans: false
      shuffle: false
      plot_overview: false
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2173/full_disk/hmi.b_720s.20160205_170000_TAI.Bp_err.fits"
      mask_configs:
        type: heliographic_carrington
        longitude_range: [ 2.336, 3.384 ]
        latitude_range: [  1.157, 2.205 ]
        invert: true
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
      longitude_range: [ 2.336, 3.384 ]
      latitude_range: [  1.157, 2.205 ]
    - type: sphere
      ds_id: sphere
      longitude_range: [ 2.336, 3.384 ]
      latitude_range: [  1.157, 2.205 ]
  max_radius: 1.3
  G_per_dB: 2000
  num_workers: 8
  batch_size: 16384
  iterations: 1000
model:
  type: vector_potential
  dim: 512
training:
  epochs: 1000
  loss_config:
    - type: boundary
      name: boundary
      lambda: {start: 1.0e+3, end: 1.0, iterations: 5.0e+4}
      ds_id: AR
    - type: energy_gradient
      lambda: 1.0
      ds_id: random
      base_radius: 1.04
    - type: potential
      lambda: 1.0e-2
      ds_id: random
      base_radius: 1.04
    - type: force_free
      lambda: 0.1
