---
base_path: "/glade/work/rjarolim/nf2/spherical/2173_series_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/2173_series_v01"
meta_path: "/glade/work/rjarolim/nf2/spherical/2173_full_v06/last.ckpt"
logging:
  project: spherical
  name: "2173 series"
data:
  type: spherical
  data_path: "/glade/work/rjarolim/data/global/fd_2173/full_disk"
  synoptic_fits_path:
      Br: "/glade/work/rjarolim/data/global/fd_2173/hmi.synoptic_mr_polfil_720s.2173.Mr_polfil.fits"
      Bt: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bt.fits"
      Bp: "/glade/work/rjarolim/data/global/fd_2173/hmi.b_synoptic.2173.Bp.fits"
  validation_configs:
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
      longitude_range: [ 1.446, 4.273 ]
      latitude_range: [  0.424, 2.938 ]
    - type: spherical_slices
      ds_id: full_sphere
      n_slices: 10
      plot_currents: true
  max_radius: 1.3
  G_per_dB: 2000
  num_workers: 8
  batch_size: 16384
  iterations: 1.0e+4
model:
  type: vector_potential
  dim: 256
training:
  loss_config:
    - type: boundary
      name: boundary
      lambda: 1.0
      ds_id: [full_disk, synoptic]
    - type: energy_gradient
      lambda: 1.0
      ds_id: random
      base_radius: 1.04
    - type: potential
      lambda: 1.0e-2
      ds_id: random
      base_radius: 1.04
    - type: force_free
      lambda: 0.1
    - type: divergence
      lambda: 0.0
