---
base_path: "/glade/work/rjarolim/nf2/spherical/2267_v04"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/2267_v04"
logging:
  project: spherical
  name: "2267 radial"
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: AR
      batch_size: 4096
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Bp_err.fits"
    - type: map
      ds_id: synoptic
      batch_size: 4096
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2267/hmi.synoptic_mr_polfil_720s.2267.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2267/hmi.b_synoptic.2267.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2267/hmi.b_synoptic.2267.Bp.fits"
      mask_configs:
        type: reference
        file: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Br.fits"
    - type: random_spherical
      ds_id: random
      batch_size: 16384
      name: random
  validation_configs:
    - type: map
      ds_id: AR_valid
      filter_nans: false
      shuffle: false
      plot_overview: false
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2267/full_disk/hmi.b_720s.20230224_190000_TAI.Bp_err.fits"
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
    - type: sphere
      ds_id: sphere
  max_radius: 1.3
  G_per_dB: 2000
  num_workers: 8
  batch_size: 65536
model:
  type: vector_potential
  dim: 512
training:
  epochs: 1000
  loss_config:
    - type: boundary
      name: boundary
      lambda: 1
      ds_id: [synoptic, AR]
    - type: force_free
      lambda: 0.1
    - type: radial
      lambda: 1.0e-4
      ds_id: [random]
      base_radius: 7.246875
  check_val_every_n_epoch: 1
