---
base_path: "/glade/work/rjarolim/nf2/spherical/comparison/377_reference_v02"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/377_reference_v02"
logging:
  project: spherical
  name: '377 spherical reference'
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: full_disk
      batch_size: 8192
      requires_jacobian: False
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bp_err.fits"
      mask_configs:
        type: mu_filter
        min: 0.2
    - type: random_radial_grouped
      ds_id: random
      batch_size: 16384
      n_lat_lon_sample: 64
      length: 1.0e+4
      radial_sampling_exponent: 2
      reference_map:
        file: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br.fits"
        mu:
          min: 0.2
  validation_configs:
    - type: map
      ds_id: full_disk_valid
      filter_nans: false
      shuffle: false
      plot_overview: false
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bp_err.fits"
      mask_configs:
        - type: mu_filter
          min: 0.2
        - type: heliographic_carrington
          longitude_range: [ 301.5, 463.5 ]
          latitude_range: [ -78.9 , 65.1 ]
          invert: true
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
    - type: fits_reference
      ds_id: fits_reference
      reference_file: "/glade/work/rjarolim/data/nf2/377/hmi.sharp_cea_720s.377.20110215_000000_TAI.Br.fits"
      n_slices: 64
      filter_nans: false
      shuffle: false
      plot_overview: false
      radius_range: [ 1.0, 1.05 ]
    - type: sphere
      ds_id: sphere
  max_radius: 1.3
  G_per_dB: 100
  num_workers: 16
  batch_size: 16384

model:
  type: vector_potential
  dim: 512
  w0_init: 1.0

training:
  epochs: 100

loss:
  - type: boundary
    name: boundary
    lambda: 1.0
    ds_id: [full_disk]
  - type: force_free
    name: force_free
    lambda: 1.0e-3
    ds_id: [ random ]
  - type: potential
    name: potential_top
    lambda: 1.0e-3
    ds_id: [ random ]
  - type: energy_gradient
    name: energy_gradient
    lambda: 1.0e-3
    ds_id: [ random ]

loss_scaling:
  - type: b_height
    name: b_height
    loss_ids: [ force_free, potential_top, energy_gradient ]
    power: 2
  - type: radial
    name: radial
    base_radius: 1.2
    max_radius: 1.3
    loss_ids: [ energy_gradient, potential_top ]

callbacks:
  - type: boundary
    name: boundary
    ds_id: full_disk_valid
    component_labels: [ r, t, p ]
  - type: metrics
    name: metrics
    ds_id: sphere
  - type: spherical_slices
    ds_id: slices
  - type: fits_comparison
    ds_id: fits_reference
