---
base_path: "/glade/work/rjarolim/nf2/spherical/377_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/377_v01"
logging:
  project: subframe_v2
  name: '377'
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: AR
      batch_size: 8192
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bp_err.fits"
      mask_configs:
        type: heliographic_carrington
        longitude_range: [ 0.3, 0.9 ]
        latitude_range: [ 1.74, 2.14 ]
        invert: true
    - type: pfss_boundary
      ds_id: pfss_boundary
      batch_size: 1024
      Br: "/glade/work/rjarolim/data/global/fd_2106/hmi.synoptic_mr_polfil_720s.2106.Mr_polfil.fits"
      mask:
        longitude_range: [ 0.3, 0.9 ]
        latitude_range: [ 1.74, 2.14 ]
    - type: random_spherical
      batch_size: 16384
      ds_id: random
      longitude_range: [ 0.3, 0.9 ]
      latitude_range: [ 1.74, 2.14 ]
  validation_configs:
    - type: map
      ds_id: AR_valid
      filter_nans: false
      shuffle: false
      plot_overview: false
      files:
        Br: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br.fits"
        Bt: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bp.fits"
        Br_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Br_err.fits"
        Bt_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bt_err.fits"
        Bp_err: "/glade/work/rjarolim/data/global/fd_2106/full_disk/hmi.b_720s.20110215_000000_TAI.Bp_err.fits"
      mask_configs:
        type: heliographic_carrington
        longitude_range: [ 0.3, 0.9 ]
        latitude_range: [ 1.74, 2.14 ]
        invert: true
    - type: spherical_slices
      ds_id: subframe_slices
      n_slices: 10
      plot_currents: true
      longitude_range: [ 0.3, 0.9 ]
      latitude_range: [ 1.74, 2.14 ]
    - type: sphere
      ds_id: sphere
      longitude_range: [ 0.3, 0.9 ]
      latitude_range: [ 1.74, 2.14 ]
  max_radius: 1.14
  G_per_dB: 2000
  num_workers: 8
  batch_size: 65536
model:
  type: b
  dim: 512
  activation: swish
training:
  epochs: 1.0e+3
  loss_config:
    - type: boundary
      name: boundary
      lambda: 10.0
      ds_id: AR
    - type: boundary
      name: potential_boundary
      lambda: 0.1
      ds_id: pfss_boundary
    - type: force_free
      lambda: 0.01
    - type: divergence
      lambda: 0.01
  check_val_every_n_epoch: 20
