---
base_path: "/glade/work/rjarolim/nf2/synoptic/{CR}_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/{CR}_v01"
logging:
  project: synoptic
  name: "{CR}"
data:
  type: spherical
  train_configs:
    - type: map
      ds_id: synoptic
      batch_size: 8192
      files:
        Br: "/glade/work/rjarolim/data/global/synoptic/hmi.synoptic_mr_polfil_720s.{CR}.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/synoptic/hmi.b_synoptic.{CR}.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/synoptic/hmi.b_synoptic.{CR}.Bp.fits"
    - type: random_spherical
      ds_id: random
      batch_size: 16384
  validation_configs:
    - type: map
      ds_id: synoptic_valid
      filter_nans: false
      shuffle: false
      plot_overview: false
      files:
        Br: "/glade/work/rjarolim/data/global/synoptic/hmi.synoptic_mr_polfil_720s.{CR}.Mr_polfil.fits"
        Bt: "/glade/work/rjarolim/data/global/synoptic/hmi.b_synoptic.{CR}.Bt.fits"
        Bp: "/glade/work/rjarolim/data/global/synoptic/hmi.b_synoptic.{CR}.Bp.fits"
    - type: spherical_slices
      ds_id: slices
      n_slices: 10
      plot_currents: true
    - type: sphere
      ds_id: sphere
  max_radius: 2.5
  G_per_dB: 2000
  num_workers: 8
  batch_size: 16384
  iterations: 10000
model:
  type: vector_potential
  dim: 512
training:
  epochs: 100
  loss_config:
    - type: boundary
      name: boundary
      lambda: {start: 1.0e+3, end: 10.0, iterations: 5.0e+4}
      ds_id: synoptic
    - type: energy_gradient
      lambda: 10.0
      ds_id: random
      base_radius: 1.04
    - type: potential
      lambda: 0.0 #1.0e-2
      ds_id: random
      base_radius: 1.04
    - type: force_free
      lambda: 0.1
    - type: radial
      lambda: 1.0e-4
      ds_id: random
      base_radius: 2.0