"""Structured reference data used by the NF2 documentation."""

from nf2.evaluation.output_metrics import OUTPUT_METRICS

CONFIG_OPTIONS = [
    ("path", "str", "./runs/nf2", "Directory for checkpoints, logs, and extrapolation_result.nf2."),
    ("work_path", "str | null", "path/work", "Optional scratch directory for preprocessed arrays."),
    ("logging", "dict", "{}", "Options passed to the Lightning/W&B logger."),
    ("logging.project", "str", "logger default", "W&B project name when W&B logging is enabled."),
    ("logging.name", "str", "logger default", "Run name shown in W&B/log output."),
    ("data.geometry", "cartesian | spherical", "required", "Extrapolation geometry."),
    ("data.normalization.Mm_per_ds", "float", "100", "Length represented by one model coordinate unit."),
    ("data.normalization.Gauss_per_dB", "float", "1000", "Magnetic-field strength represented by one model field unit."),
    ("data.boundaries", "list[dict]", "required", "Boundary observations, analytical fields, or maps."),
    ("data.boundaries[].id", "str", "boundary / generated", "Stable dataset id used by losses, transforms, callbacks, and series references."),
    ("data.boundaries[].type", "str", "required", "Dataset implementation name. See the dataset reference for supported types."),
    ("data.boundaries[].files", "dict | list[dict] | glob", "dataset dependent", "Input file mapping or series file mapping for observational datasets."),
    ("data.boundaries[].errors", "dict | list[dict]", "optional", "Optional uncertainty-file mapping. Bundled templates skip unresolved error placeholders."),
    ("data.boundaries[].batch_size", "int", "data batch size", "Per-dataset batch size override."),
    ("data.boundaries[].requires_jacobian", "bool", "dataset dependent", "Whether this dataset must provide derivatives for losses or callbacks."),
    ("data.boundaries[].Mm_per_pixel", "float", "dataset default", "Spatial sampling for this boundary in Mm per pixel."),
    ("data.boundaries[].coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate assigned to the boundary center, in Mm."),
    ("data.boundaries[].height_mapping", "dict", "none", "Height metadata for multi-height Cartesian boundary datasets."),
    ("data.boundaries[].mask_configs", "dict | list[dict]", "none", "Spherical map masking/filtering configuration."),
    ("data.boundaries[].mask_configs.type", "str", "mask dependent", "Mask/filter implementation name, for example `mu_filter` or `reference`."),
    ("data.boundaries[].mask_configs.min", "float", "mask dependent", "Minimum value for simple threshold-style masks such as `mu_filter`."),
    ("data.boundaries[].mask_configs.file", "str", "required for reference masks", "Reference map file used by spherical `reference` masks."),
    ("data.boundaries[].mask_configs.mu_filter", "dict", "optional", "Nested mu-angle filter applied inside a spherical `reference` mask."),
    ("data.boundaries[].mask_configs.mu_filter.min", "float", "mask dependent", "Minimum mu value for the nested reference-mask filter."),
    ("data.boundaries[].mask_configs[].type", "str", "mask dependent", "Mask/filter implementation name when masks are provided as a list."),
    ("data.boundaries[].mask_configs[].min", "float", "mask dependent", "Minimum value when list-form masks use `mu_filter`."),
    ("data.validation", "list[dict]", "geometry default", "Validation grids and plotting datasets."),
    ("data.validation[].id", "str", "generated", "Stable validation dataset id used by callbacks."),
    ("data.validation[].type", "str", "required", "Validation dataset implementation name."),
    ("data.validation[].files", "dict | list[dict] | glob", "dataset dependent", "Input file mapping for validation datasets."),
    ("data.validation[].errors", "dict | list[dict]", "optional", "Optional validation uncertainty-file mapping."),
    ("data.validation[].filter_nans", "bool", "dataset default", "Whether to filter NaN samples in spherical map validation datasets."),
    ("data.validation[].shuffle", "bool", "dataset default", "Whether to shuffle validation samples."),
    ("data.validation[].plot_overview", "bool", "dataset default", "Whether to prepare overview plots for spherical map validation datasets."),
    ("data.validation[].plot_currents", "bool", "dataset default", "Whether spherical slice validation plots include current-density views."),
    ("data.validation[].n_slices", "int", "dataset default", "Number of slices for slice-based validation datasets."),
    ("data.validation[].mask_configs.type", "str", "mask dependent", "Mask/filter implementation name for validation map datasets."),
    ("data.validation[].mask_configs.min", "float", "mask dependent", "Minimum value for validation threshold-style masks such as `mu_filter`."),
    ("data.validation[].mask_configs[].type", "str", "mask dependent", "Mask/filter implementation name when validation masks are provided as a list."),
    ("data.validation[].mask_configs[].min", "float", "mask dependent", "Minimum value when list-form validation masks use `mu_filter`."),
    ("data.batch_size", "int", "4096 spherical, 8192 cartesian", "Default dataset batch size passed to loaders."),
    ("data.validation_batch_size", "int", "16384", "Cartesian validation batch size."),
    ("data.validation_pixel_per_ds", "float", "128", "Cartesian validation sampling density; larger values make coarser validation cubes."),
    ("data.sampler", "dict", "height sampler", "Cartesian physics sampling dataset."),
    ("data.sampler.type", "height | default", "height", "Cartesian random sampler type."),
    ("data.sampler.batch_size", "int", "16384 in examples", "Cartesian random sampler batch size."),
    ("data.samplers", "list[dict]", "random_radial_grouped", "Spherical physics sampling datasets."),
    ("data.samplers[].id", "str", "random", "Spherical sampler id used by losses."),
    ("data.samplers[].type", "random_radial_grouped | random_spherical", "random_radial_grouped", "Spherical random sampler type."),
    ("data.samplers[].batch_size", "int", "data.batch_size", "Spherical random sampler batch size."),
    ("data.potential_boundary", "dict", "FFT potential", "Cartesian potential boundary data. Use type: none to disable."),
    ("data.potential_boundary.id", "str", "ignored", "Accepted for readability; normalized away because the runtime id is `potential`."),
    ("data.potential_boundary.type", "potential | potential_top | none", "potential", "Potential side/top boundary mode."),
    ("data.potential_boundary.strides", "int", "4", "Downsample factor for potential boundary generation."),
    ("data.z_range", "list[float]", "loader default", "Cartesian height range in Mm where supported by the loader."),
    ("data.max_radius", "float", "loader default", "Spherical outer radius in solar radii where supported by the loader."),
    ("data.iterations", "int", "10000", "Number of random sampler batches per epoch-like pass."),
    ("data.num_workers", "int", "4", "Default PyTorch DataLoader workers for training and validation loaders. Series preloading uses this value unless data.data_module_workers is set."),
    ("data.train_num_workers", "int", "data.num_workers", "PyTorch DataLoader workers for training loaders."),
    ("data.validation_num_workers", "int", "data.num_workers", "PyTorch DataLoader workers for validation loaders."),
    ("data.prefetch_factor", "int", "5", "Training DataLoader prefetch factor when workers are enabled."),
    ("data.persistent_workers", "bool", "true", "Keep training DataLoader workers alive while a loader is active."),
    ("data.preload_data_modules", "bool", "true", "For series runs, preload all step data modules up front instead of loading each step lazily."),
    ("data.data_module_workers", "int", "data.num_workers", "Series-only multiprocessing workers used to preload per-step data modules."),
    ("model.field", "vector_potential | scaled_vector_potential | b", "vector_potential", "Field representation."),
    ("model.network.type", "siren", "siren", "Only SIREN networks are supported."),
    ("model.network.hidden_dim", "int", "256 cartesian, 512 spherical", "SIREN hidden width."),
    ("model.network.layers", "int", "model default", "Number of SIREN layers."),
    ("model.network.w0", "float", "model default", "SIREN frequency scale for hidden layers."),
    ("model.network.w0_initial", "float", "model default", "SIREN frequency scale for the first layer."),
    ("model.radial_power", "float", "2.0", "Radial power for `scaled_vector_potential`, applied as `(r / R_sun)^-radial_power`."),
    ("model.coordinate_radial_power", "float", "4.0", "Radial power for compressing SIREN input coordinates in `scaled_vector_potential`, applied as `coords * (r / R_sun)^-coordinate_radial_power`."),
    ("model.base_radius", "float", "R_sun in model units", "Reference radius for `scaled_vector_potential`; omit for spherical runs."),
    ("training.epochs", "int", "15", "Number of Lightning epochs."),
    ("training.optimizer.start", "float", "5e-4", "Initial learning rate."),
    ("training.optimizer.end", "float", "5e-5", "Final learning rate."),
    ("training.optimizer.iterations", "int", "100000", "Learning-rate schedule length."),
    ("training.gradient_clip_val", "float", "0.1", "Gradient clipping value passed to the Lightning Trainer unless overridden in training.trainer."),
    ("training.matmul_precision", "str", "medium", "Torch matmul precision setting used before training."),
    ("training.reload_dataloaders_every_n_epochs", "int", "1 for series", "Series cadence for advancing to the next dataset."),
    ("training.check_val_every_n_epoch", "int", "1", "Lightning validation cadence. Series examples use 10 to validate every 10th dataset."),
    ("training.val_check_interval", "int | float", "Lightning default", "Optional Lightning validation interval alias used by single-run training."),
    ("training.trainer", "dict", "{}", "Additional Lightning Trainer keyword arguments."),
    ("training.trainer.*", "any", "Lightning default", "Additional keyword passed through to `lightning.pytorch.Trainer`."),
    ("losses", "list[dict]", "geometry default", "Training objective terms. Omit to use geometry-specific defaults."),
    ("losses[].type", "str", "geometry default", "Loss implementation name. Supported values are boundary, boundary_los_trv, boundary_azi, boundary_los_trv_azi, boundary_los, divergence, force_free, potential, weighted_height, height, NaNs, radial, min_height, energy_gradient, energy, sigma_j."),
    ("losses[].name", "str", "type", "Stable logging and scaling identifier."),
    ("losses[].weight", "float | schedule", "required when explicit", "Loss weight. The legacy lambda key is not accepted."),
    ("losses[].weight.type", "exponential | linear | step", "exponential", "Schedule type when `weight` is a mapping."),
    ("losses[].weight.start", "float", "required for exponential/linear", "Initial scheduled loss weight."),
    ("losses[].weight.end", "float", "required for scheduled weights", "Final scheduled loss weight."),
    ("losses[].weight.iterations", "int", "required for exponential/linear", "Number of optimizer steps over which to change the weight."),
    ("losses[].weight.steps", "int", "required for step", "Step interval for step schedules."),
    ("losses[].datasets", "str | list[str]", "loss default", "Dataset ids used by the loss."),
    ("losses[].ambiguous", "bool", "loss default", "Enable ambiguity-aware behavior for supported azimuth/disambiguation losses."),
    ("loss_scaling", "list[dict]", "geometry default", "Spatial scaling modules for selected losses."),
    ("loss_scaling[].type", "exponential | potential_fit | b_height | radial", "geometry default", "Loss-scaling module type."),
    ("loss_scaling[].name", "str", "type", "Stable loss-scaling module name."),
    ("loss_scaling[].loss_ids", "list[str]", "required", "Loss names to scale."),
    ("loss_scaling[].base_radius", "float", "1.1 radial default", "Solar-radius baseline for radial scaling."),
    ("loss_scaling[].max_radius", "float | null", "none", "Optional outer radius used to normalize radial scaling."),
    ("loss_scaling[].power", "float", "module default", "Exponent used by b_height or potential_fit scaling."),
    ("callbacks", "list[dict]", "geometry default", "Validation plots and metrics logged during training."),
    ("callbacks[].type", "boundary | metrics | slices | spherical_slices | fits_comparison | disambiguation | los_trv_azi_boundary", "required", "Callback implementation name."),
    ("callbacks[].dataset", "str", "required for most callbacks", "Public alias for validation dataset id; normalized internally to `ds_id`."),
    ("callbacks[].name", "str", "callback default", "Optional display/logging name for callbacks that support it."),
    ("callbacks[].plot", "bool", "true", "For plotting callbacks, set false to keep scalar metrics but skip image rendering/logging."),
    ("callbacks[].component_labels", "list[str]", "callback default", "Optional labels for vector-component plots."),
    ("transforms", "list[dict]", "[]", "Optional coordinate/field transforms applied to datasets."),
    ("transforms[].type", "height_range | height | optical_depth | azimuth", "required", "Transform implementation name."),
    ("transforms[].datasets", "str | list[str]", "required", "Dataset ids to transform; normalized internally to `ds_id`."),
    ("transforms[].height_range", "list[float]", "required for height", "Height range in Mm for learned height transforms."),
    ("transforms[].max_height", "float", "required for optical_depth", "Maximum optical-depth transform height in Mm."),
    ("transforms[].max_log_optical_depth", "float", "-5", "Maximum log optical depth for optical-depth transforms."),
    ("meta_path", "str", "none", "Optional previous NF2 state used by series runs."),
]


DATASET_TYPES = [
    ("analytical", "benchmark boundary", "Low & Lou analytical fields for case1/case2 benchmarks."),
    ("sharp", "cartesian boundary", "SHARP CEA Br/Bt/Bp FITS input, optionally with uncertainty maps."),
    ("fits", "cartesian boundary", "Generic Cartesian Br/Bt/Bp FITS files."),
    ("los_trv_azi", "cartesian boundary", "LOS/transverse/azimuth FITS input with automatic disambiguation support."),
    ("los", "cartesian boundary", "Line-of-sight-only Cartesian boundary input."),
    ("fld_inc_azi", "cartesian boundary", "Field strength/inclination/azimuth FITS input."),
    ("numpy", "cartesian boundary", "Preprocessed NumPy Cartesian vector-field input."),
    ("muram_slice", "cartesian boundary", "MURaM slice boundary input."),
    ("muram_cube", "cartesian boundary", "MURaM cube boundary input."),
    ("height", "cartesian sampler", "Random Cartesian volume samples for force-free and potential losses."),
    ("potential", "cartesian boundary", "Potential-field boundary generated from the photospheric boundary."),
    ("map", "spherical boundary", "Spherical Br/Bt/Bp map input for full-disk or synoptic maps."),
    ("random_radial_grouped", "spherical sampler", "Grouped radial samples in the spherical volume."),
    ("random_spherical", "spherical sampler", "Ungrouped random samples in the spherical volume."),
    ("fits_reference", "spherical validation", "Reference spherical FITS comparison dataset."),
    ("sphere", "spherical validation", "Spherical validation grid for field-quality callbacks."),
    ("spherical_slices", "spherical validation", "Radial or angular slices for spherical visualization callbacks."),
]

DATASET_KEYS = [
    (
        "analytical",
        "benchmark boundary",
        [
            ("case", "int | str", "1", "Analytical Low & Lou case identifier."),
            ("boundary", "full | bottom", "full", "Use the full analytical volume as a boundary dataset or only the lower boundary for validation."),
            ("bounds", "list[float]", "loader default", "Physical Cartesian volume bounds for the benchmark field."),
            ("resolution", "int | list[int]", "loader default", "Sampling resolution used to generate the benchmark boundary."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training batch."),
        ],
    ),
    (
        "sharp",
        "cartesian boundary or validation",
        [
            ("files.Br", "str", "required", "Radial magnetic-field FITS file."),
            ("files.Bt", "str", "required", "Theta/transverse magnetic-field FITS file."),
            ("files.Bp", "str", "required", "Phi/azimuthal magnetic-field FITS file."),
            ("errors.Br_err", "str", "optional", "Radial uncertainty FITS file."),
            ("errors.Bt_err", "str", "optional", "Theta/transverse uncertainty FITS file."),
            ("errors.Bp_err", "str", "optional", "Phi/azimuthal uncertainty FITS file."),
            ("Mm_per_pixel", "float", "FITS/WCS default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("slice", "slice | null", "null", "Optional image subset."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "fits",
        "cartesian boundary or validation",
        [
            ("files.Br", "str", "required", "Radial/vertical magnetic-field FITS file."),
            ("files.Bt", "str", "required", "Transverse x/theta component FITS file."),
            ("files.Bp", "str", "required", "Transverse y/phi component FITS file."),
            ("errors.Br_err", "str", "optional", "Vertical-component uncertainty FITS file."),
            ("errors.Bt_err", "str", "optional", "Transverse x/theta uncertainty FITS file."),
            ("errors.Bp_err", "str", "optional", "Transverse y/phi uncertainty FITS file."),
            ("load_map", "bool", "dataset default", "Load FITS as SunPy maps when coordinate metadata are needed."),
            ("Mm_per_pixel", "float", "dataset default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "los_trv_azi",
        "cartesian boundary or validation",
        [
            ("files.B_los", "str", "required", "Line-of-sight magnetic-field FITS file."),
            ("files.B_trv", "str", "required", "Transverse-field magnitude FITS file."),
            ("files.B_azi", "str", "required", "Azimuth FITS file."),
            ("ambiguous_azimuth", "bool", "false", "Train/evaluate both azimuth disambiguation branches when supported by the loss."),
            ("load_map", "bool", "dataset default", "Load map metadata for coordinate conversion and plotting."),
            ("height_mapping", "dict", "none", "Map this boundary to a height or learned height range, for multi-height runs."),
            ("Mm_per_pixel", "float", "dataset default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "los",
        "cartesian boundary or validation",
        [
            ("files.B_los", "str", "required", "Line-of-sight magnetic-field FITS file."),
            ("Mm_per_pixel", "float", "dataset default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "fld_inc_azi",
        "cartesian boundary or validation",
        [
            ("files.B_fld", "str", "required", "Field-strength FITS file."),
            ("files.B_inc", "str", "required", "Inclination FITS file."),
            ("files.B_azi", "str", "required", "Azimuth FITS file."),
            ("Mm_per_pixel", "float", "dataset default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "height",
        "cartesian sampler",
        [
            ("batch_size", "int", "16384 in examples", "Random volume samples per training batch."),
            ("type", "height | default", "height", "Height-biased sampler or uniform Cartesian sampler."),
            ("z_sample", "int", "128", "Number of heights sampled per xy location."),
            ("z_sampling_exponent", "float", "2", "Bias random samples toward lower heights when greater than 1."),
            ("length", "int | null", "data.iterations", "Number of sampler batches per epoch-like pass."),
            ("requires_jacobian", "bool", "true", "Required for force-free, divergence, and potential losses."),
        ],
    ),
    (
        "potential",
        "cartesian potential boundary",
        [
            ("type", "potential | potential_top | none", "potential", "Potential-field side/top boundary mode."),
            ("strides", "int", "4", "Downsample factor for generating the potential boundary."),
            ("method", "fft | direct", "fft", "Potential-field solver."),
            ("batch_size", "int", "boundary batch size / 4", "Potential boundary samples per batch."),
            ("requires_jacobian", "bool", "false", "Usually disabled for boundary matching."),
        ],
    ),
    (
        "cube",
        "cartesian validation",
        [
            ("ds_per_pixel", "float", "1 / validation_pixel_per_ds", "Validation grid spacing in model units."),
            ("batch_size", "int", "validation_batch_size", "Validation samples per batch."),
            ("requires_jacobian", "bool", "true", "Needed for quality metrics that use derivatives."),
        ],
    ),
    (
        "slices",
        "cartesian validation",
        [
            ("n_slices", "int", "10", "Number of height slices to evaluate and plot."),
            ("batch_size", "int", "4096", "Validation samples per batch."),
            ("requires_jacobian", "bool", "true", "Needed for current-density plots."),
        ],
    ),
    (
        "map",
        "spherical boundary or validation",
        [
            ("files.Br", "str", "required", "Radial magnetic-field map."),
            ("files.Bt", "str", "required", "Theta magnetic-field map."),
            ("files.Bp", "str", "required", "Phi magnetic-field map."),
            ("errors.Br_err", "str", "optional", "Radial uncertainty map, merged into the file map internally."),
            ("errors.Bt_err", "str", "optional", "Theta uncertainty map, merged into the file map internally."),
            ("errors.Bp_err", "str", "optional", "Phi uncertainty map, merged into the file map internally."),
            ("mask_configs", "dict", "optional", "Optional masking/filtering, for example a `mu_filter`."),
            ("filter_nans", "bool", "dataset default", "Whether to filter NaN samples."),
            ("shuffle", "bool", "dataset default", "Whether to shuffle map samples."),
            ("plot_overview", "bool", "dataset default", "Whether to prepare overview plots."),
            ("batch_size", "int", "data.batch_size or dataset default", "Map samples per batch."),
            ("requires_jacobian", "bool", "false for boundary examples", "Enable only when the dataset feeds derivative-based losses."),
        ],
    ),
    (
        "random_radial_grouped",
        "spherical sampler",
        [
            ("batch_size", "int", "16384 in examples", "Random spherical volume samples per batch."),
            ("n_lat_lon_sample", "int", "128", "Number of angular samples; `batch_size` must be divisible by this value."),
            ("radial_sampling_exponent", "float", "1", "Bias radial samples when greater than 1."),
            ("latitude_range", "list[float]", "[-90, 90]", "Latitude range in degrees unless `unit` is changed."),
            ("longitude_range", "list[float]", "[0, 360]", "Longitude range in degrees unless `unit` is changed."),
            ("length", "int | null", "data.iterations", "Internal sampler length; public YAML should usually use data.iterations."),
            ("requires_jacobian", "bool", "true", "Required for force-free, potential, and energy-gradient losses."),
        ],
    ),
    (
        "random_spherical",
        "spherical sampler",
        [
            ("batch_size", "int", "data.batch_size", "Random spherical volume samples per batch."),
            ("latitude_range", "list[float]", "[-90, 90]", "Latitude range in degrees unless `unit` is changed."),
            ("longitude_range", "list[float]", "[0, 360]", "Longitude range in degrees unless `unit` is changed."),
            ("length", "int | null", "data.iterations", "Internal sampler length; public YAML should usually use data.iterations."),
            ("requires_jacobian", "bool", "true", "Required for force-free, potential, and energy-gradient losses."),
        ],
    ),
    (
        "sphere",
        "spherical validation",
        [
            ("resolution", "int", "256", "Radial and longitude resolution of the validation sphere."),
            ("batch_size", "int", "1024", "Validation samples per batch."),
            ("latitude_range", "list[float]", "[-90, 90]", "Latitude range in degrees unless `unit` is changed."),
            ("longitude_range", "list[float]", "[0, 360]", "Longitude range in degrees unless `unit` is changed."),
            ("requires_jacobian", "bool", "true", "Needed for derivative-based quality metrics."),
        ],
    ),
    (
        "spherical_slices",
        "spherical validation",
        [
            ("longitude_resolution", "int", "256", "Longitude resolution for slice plots."),
            ("n_slices", "int", "5", "Number of radial slices."),
            ("plot_currents", "bool", "false", "Include current-density plots in spherical slice callbacks when available."),
            ("batch_size", "int", "1024", "Validation samples per batch."),
            ("latitude_range", "list[float]", "[-90, 90]", "Latitude range in degrees unless `unit` is changed."),
            ("longitude_range", "list[float]", "[0, 360]", "Longitude range in degrees unless `unit` is changed."),
            ("requires_jacobian", "bool", "true", "Needed for current-density plots."),
        ],
    ),
    (
        "fits_reference",
        "spherical validation",
        [
            ("file", "str", "required", "Reference FITS file."),
            ("fits_reference_Br", "str", "template placeholder", "Common placeholder used by bundled spherical examples for reference Br files."),
            ("batch_size", "int", "data.batch_size", "Validation samples per batch."),
            ("requires_jacobian", "bool", "false", "Usually disabled for reference comparisons."),
        ],
    ),
]


CLI_COMMANDS = [
    (
        "nf2-extrapolate",
        "Run one YAML-configured extrapolation.",
        [
            ("--config", "required", "Path to a YAML configuration file."),
            ("--<placeholder>", "optional", "Fills <<placeholder>> or <<placeholder;default>> before YAML parsing. CLI values take precedence, defaults are used when omitted, and missing placeholders without defaults raise an error. Multiple values are supported for list placeholders such as --z_range 0 150."),
        ],
    ),
    (
        "nf2-extrapolate-series",
        "Run a YAML-configured time series.",
        [
            ("--config", "required", "Path to a series YAML configuration file."),
            ("--reload", "false", "Rebuild work_path/data_module.pkl instead of reusing the saved series data module state."),
            ("--<placeholder>", "optional", "Fills <<placeholder>> or <<placeholder;default>> before YAML parsing. CLI values take precedence, defaults are used when omitted, and missing placeholders without defaults raise an error. Supports glob patterns and multi-value list placeholders."),
        ],
    ),
    (
        "nf2-download",
        "Download supported JSOC/HMI data sources.",
        [
            ("--source", "hmi_sharp", "One of hmi_sharp, hmi_synoptic, hmi_full_disk."),
            ("--download_dir", "required", "Output directory."),
            ("--email", "required", "JSOC export email address."),
            ("--sharp_num", "none", "HARP/SHARP number for hmi_sharp."),
            ("--noaa_num", "none", "NOAA active-region number, resolved to HARP when needed."),
            ("--t_start", "source dependent", "Start time for hmi_sharp, hmi_full_disk, or Carrington-rotation lookup for hmi_synoptic."),
            ("--t_end", "none", "Optional end time; for hmi_synoptic this resolves an inclusive rotation range."),
            ("--cadence", "720s", "Cadence for time-range downloads."),
            ("--series", "source default", "JSOC series override."),
            ("--segments", "source default", "Comma-separated JSOC segments."),
            ("--carrington_rotation", "none", "Carrington rotation for hmi_synoptic; alternatively provide --t_start."),
            ("--carrington_rotation_end", "same as start", "Optional inclusive final Carrington rotation."),
            ("--synoptic_product", "vector", "One of vector, mr_polfil, both for hmi_synoptic."),
            ("--include_mr_polfil", "false", "Also download hmi.synoptic_mr_polfil_720s Mr_polfil for synoptic-map runs."),
            ("--no_convert_ptr", "false", "Disable HmiB2ptr conversion for full-disk vector data."),
            ("--keep_coordinates", "false", "Keep generated latitude/longitude files after full-disk conversion."),
        ],
    ),
    (
        "nf2-export",
        "Export NF2 results to exchange formats.",
        [
            ("nf2_path", "required", "One or more .nf2 paths or glob patterns."),
            ("--format", "vtk", "One of vtk, npz, hdf5, h5, fits, height, height-npz, height_npz."),
            ("--out", "none", "Output file for a single input."),
            ("--out-dir", "current directory", "Output directory for multiple inputs."),
            ("--Mm_per_pixel", "checkpoint default", "Cartesian export sampling."),
            ("--height_range", "full height", "Cartesian height range in Mm."),
            ("--x_range", "full x", "Cartesian x range in Mm."),
            ("--y_range", "full y", "Cartesian y range in Mm."),
            ("--radius_range", "0.999 1.3", "Spherical VTK radius range in solar radii."),
            ("--latitude_range", "-90 90", "Spherical VTK latitude range in degrees."),
            ("--longitude_range", "0 360", "Spherical VTK longitude range in degrees."),
            ("--pixels_per_solRad", "64", "Spherical VTK sampling resolution."),
            ("--metrics", "j", "Derived quantities to include."),
            ("--overwrite", "false", "Replace existing series export files."),
        ],
    ),
    (
        "nf2-metrics",
        "Print standard NLFF quality metrics.",
        [
            ("nf2_path", "required", "Path to extrapolation_result.nf2."),
            ("--device", "auto", "PyTorch evaluation device."),
            ("--progress", "false", "Show evaluation progress."),
            ("--batch_size", "output default", "Evaluation batch size."),
            ("--Mm_per_pixel", "checkpoint default", "Cartesian sampling."),
            ("--height_range", "full height", "Cartesian height range in Mm."),
            ("--x_range", "full x", "Cartesian x range in Mm."),
            ("--y_range", "full y", "Cartesian y range in Mm."),
            ("--spherical_sampling", "32 64 128", "Spherical radial, latitude, longitude sample counts."),
            ("--radius_range", "checkpoint range", "Spherical radius range in solar radii."),
            ("--latitude_range", "-90 90", "Spherical latitude range in degrees."),
            ("--longitude_range", "0 360", "Spherical longitude range in degrees."),
        ],
    ),
    (
        "nf2-noaa-to-sharp",
        "Resolve NOAA active-region numbers to SHARP/HARP numbers through JSOC metadata.",
        [
            ("--time", "required", "Observation time used for the NOAA-to-HARP lookup."),
            ("--email", "required", "JSOC export email address."),
            ("--noaa_nums", "all active regions", "One or more NOAA active-region numbers to resolve."),
        ],
    ),
]


EXPORT_METRICS = [
    (metric.name, ", ".join(metric.outputs), metric.description)
    for metric in OUTPUT_METRICS.values()
]


QUALITY_METRICS = [
    ("mean_abs_divB", "Mean absolute divergence in G/Mm."),
    ("rms_divB", "Root-mean-square divergence in G/Mm."),
    ("mean_abs_divB_over_B", "Mean |div B| / |B| in 1/Mm."),
    ("rms_divB_over_B", "Root-mean-square |div B| / |B| in 1/Mm."),
    ("theta_J", "Current-weighted angle between J and B in degrees."),
    ("sigma_J", "Current-weighted sine of the J-B angle."),
    ("CWsin", "Alias for sigma_J used in NLFF comparisons."),
    ("mean_force_free_residual", "Mean |J x B| / |B|."),
    ("rms_force_free_residual", "Root-mean-square |J x B| / |B|."),
    ("E_tot", "Total magnetic energy."),
    ("E_free", "Free magnetic energy. Cartesian uses the FFT potential-field reference."),
    ("E_pot", "Potential magnetic energy estimate E_tot - E_free."),
    ("E_free_over_E_tot", "Free-energy fraction."),
    ("mean_B", "Mean magnetic-field strength."),
    ("max_B", "Maximum magnetic-field strength."),
]
