"""Structured reference data used by the NF2 documentation."""

CONFIG_OPTIONS = [
    ("path", "str", "./runs/nf2", "Directory for checkpoints, logs, and extrapolation_result.nf2."),
    ("work_path", "str | null", "path/work", "Optional scratch directory for preprocessed arrays."),
    ("logging", "dict", "{}", "Options passed to the Lightning/W&B logger."),
    ("data.geometry", "cartesian | spherical", "required", "Extrapolation geometry."),
    ("data.normalization.Mm_per_ds", "float", "100", "Length represented by one model coordinate unit."),
    ("data.normalization.Gauss_per_dB", "float", "1000", "Magnetic-field strength represented by one model field unit."),
    ("data.boundaries", "list[dict]", "required", "Boundary observations, analytical fields, or maps."),
    ("data.boundaries[].Mm_per_pixel", "float", "dataset default", "Spatial sampling for this boundary in Mm per pixel."),
    ("data.boundaries[].coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate assigned to the boundary center, in Mm."),
    ("data.validation", "list[dict]", "geometry default", "Validation grids and plotting datasets."),
    ("data.sampler", "dict", "height sampler", "Cartesian physics sampling dataset."),
    ("data.samplers", "list[dict]", "random_radial_grouped", "Spherical physics sampling datasets."),
    ("data.potential_boundary", "dict", "FFT potential", "Cartesian potential boundary data. Use type: none to disable."),
    ("data.z_range", "list[float]", "loader default", "Cartesian height range in Mm where supported by the loader."),
    ("data.max_radius", "float", "loader default", "Spherical outer radius in solar radii where supported by the loader."),
    ("data.iterations", "int", "loader default", "Number of random sampler batches for Cartesian training."),
    ("model.field", "vector_potential | b", "vector_potential", "Field representation."),
    ("model.network.type", "siren", "siren", "Only SIREN networks are supported."),
    ("model.network.hidden_dim", "int", "256 cartesian, 512 spherical", "SIREN hidden width."),
    ("model.network.layers", "int", "model default", "Number of SIREN layers."),
    ("model.network.w0", "float", "model default", "SIREN frequency scale for hidden layers."),
    ("model.network.w0_initial", "float", "model default", "SIREN frequency scale for the first layer."),
    ("training.epochs", "int", "10", "Number of Lightning epochs."),
    ("training.optimizer.start", "float", "5e-4", "Initial learning rate."),
    ("training.optimizer.end", "float", "5e-5", "Final learning rate."),
    ("training.optimizer.iterations", "int", "100000", "Learning-rate schedule length."),
    ("training.trainer", "dict", "{}", "Additional Lightning Trainer keyword arguments."),
    ("losses[].type", "str", "geometry default", "Loss implementation name."),
    ("losses[].name", "str", "type", "Stable logging and scaling identifier."),
    ("losses[].weight", "float | schedule", "required when explicit", "Loss weight. The legacy lambda key is not accepted."),
    ("losses[].datasets", "str | list[str]", "loss default", "Dataset ids used by the loss."),
    ("loss_scaling", "list[dict]", "geometry default", "Spatial scaling modules for selected losses."),
    ("callbacks", "list[dict]", "geometry default", "Validation plots and metrics logged during training."),
    ("transforms", "list[dict]", "[]", "Optional coordinate/field transforms applied to datasets."),
    ("meta_path", "str", "none", "Optional previous NF2 state used by series runs."),
]


DATASET_TYPES = [
    ("analytical", "benchmark boundary", "Low & Lou analytical fields for case1/case2 benchmarks."),
    ("sharp", "cartesian boundary", "SHARP CEA Br/Bt/Bp FITS input, optionally with uncertainty maps."),
    ("fits", "cartesian boundary", "Generic Cartesian Br/Bt/Bp FITS files."),
    ("los_trv_azi", "cartesian boundary", "LOS/transverse/azimuth FITS input with automatic disambiguation support."),
    ("los", "cartesian boundary", "Line-of-sight-only Cartesian boundary input."),
    ("fld_inc_azi", "cartesian boundary", "Field strength/inclination/azimuth FITS input."),
    ("height", "cartesian sampler", "Random Cartesian volume samples for force-free and potential losses."),
    ("potential", "cartesian boundary", "Potential-field boundary generated from the photospheric boundary."),
    ("map", "spherical boundary", "Spherical Br/Bt/Bp map input for full-disk or synoptic maps."),
    ("random_radial_grouped", "spherical sampler", "Grouped radial samples in the spherical volume."),
    ("sphere", "spherical validation", "Spherical validation grid for field-quality callbacks."),
    ("spherical_slices", "spherical validation", "Radial or angular slices for spherical visualization callbacks."),
]


CLI_COMMANDS = [
    (
        "nf2-extrapolate",
        "Run one YAML-configured extrapolation.",
        [
            ("--config", "required", "Path to a YAML configuration file."),
            ("--<placeholder>", "optional", "Any command-line option matching a <<placeholder>> in the YAML fills that value."),
        ],
    ),
    (
        "nf2-extrapolate-series",
        "Run a YAML-configured time series.",
        [
            ("--config", "required", "Path to a series YAML configuration file."),
            ("--<placeholder>", "optional", "Fills matching <<placeholder>> values, including glob patterns for series files."),
        ],
    ),
    (
        "nf2-download",
        "Download supported JSOC/HMI data sources.",
        [
            ("--source", "hmi_sharp", "One of hmi_sharp, hmi_synoptic, hmi_full_disk."),
            ("--download_dir", "required", "Output directory."),
            ("--email", "required", "JSOC export email address."),
            ("--sharp_num", "none", "HARP/SHARP number for hmi_sharp."),
            ("--noaa_num", "none", "NOAA active-region number, resolved to HARP when needed."),
            ("--t_start", "source dependent", "Start time for hmi_sharp and hmi_full_disk."),
            ("--t_end", "none", "Optional end time."),
            ("--cadence", "720s", "Cadence for time-range downloads."),
            ("--series", "source default", "JSOC series override."),
            ("--segments", "source default", "Comma-separated JSOC segments."),
            ("--carrington_rotation", "none", "Required for hmi_synoptic."),
            ("--carrington_rotation_end", "same as start", "Optional inclusive final Carrington rotation."),
            ("--include_mr_polfil", "false", "Also download hmi.synoptic_mr_polfil_720s for synoptic workflows."),
            ("--no_convert_ptr", "false", "Disable HmiB2ptr conversion for full-disk vector data."),
            ("--keep_coordinates", "false", "Keep generated latitude/longitude files after full-disk conversion."),
        ],
    ),
    (
        "nf2-export",
        "Export NF2 results to exchange formats.",
        [
            ("nf2_path", "required", "One or more .nf2 paths or glob patterns."),
            ("--format", "vtk", "One of vtk, npz, hdf5, h5, fits."),
            ("--out", "none", "Output file for a single input."),
            ("--out-dir", "current directory", "Output directory for multiple inputs."),
            ("--Mm_per_pixel", "checkpoint default", "Cartesian export sampling."),
            ("--height_range", "full height", "Cartesian height range in Mm."),
            ("--x_range", "full x", "Cartesian x range in Mm."),
            ("--y_range", "full y", "Cartesian y range in Mm."),
            ("--metrics", "j", "Derived quantities to include."),
            ("--overwrite", "false", "Replace existing series export files."),
        ],
    ),
    (
        "nf2-metrics",
        "Print standard NLFF quality metrics.",
        [
            ("nf2_path", "required", "Path to extrapolation_result.nf2."),
            ("--device", "auto", "PyTorch evaluation device."),
            ("--progress", "false", "Show evaluation progress."),
            ("--batch_size", "output default", "Evaluation batch size."),
            ("--Mm_per_pixel", "checkpoint default", "Cartesian sampling."),
            ("--height_range", "full height", "Cartesian height range in Mm."),
            ("--x_range", "full x", "Cartesian x range in Mm."),
            ("--y_range", "full y", "Cartesian y range in Mm."),
            ("--spherical_sampling", "32 64 128", "Spherical radial, latitude, longitude sample counts."),
            ("--radius_range", "checkpoint range", "Spherical radius range in solar radii."),
            ("--latitude_range", "-90 90", "Spherical latitude range in degrees."),
            ("--longitude_range", "0 360", "Spherical longitude range in degrees."),
        ],
    ),
]


EXPORT_METRICS = [
    ("j", "Current-density vector."),
    ("alpha", "Force-free alpha proxy |J| / |B|."),
    ("b_nabla_bz", "Vertical magnetic tension-related derivative."),
    ("energy", "Magnetic energy density."),
    ("energy_gradient", "Cartesian magnetic-energy gradient."),
    ("spherical_energy_gradient", "Spherical magnetic-energy gradient."),
    ("free_energy", "Free magnetic energy density using the default potential-field method."),
    ("free_energy_fft", "Free magnetic energy density using the Cartesian FFT potential field."),
    ("free_energy_direct", "Free magnetic energy density using the direct potential-field method."),
    ("magnetic_helicity", "Magnetic helicity diagnostic."),
    ("los_trv_azi", "LOS/transverse/azimuth field components."),
    ("squashing_factor", "Squashing factor and twist diagnostics."),
]


QUALITY_METRICS = [
    ("mean_abs_divB", "Mean absolute divergence in G/Mm."),
    ("rms_divB", "Root-mean-square divergence in G/Mm."),
    ("mean_abs_divB_over_B", "Mean |div B| / |B| in 1/Mm."),
    ("rms_divB_over_B", "Root-mean-square |div B| / |B| in 1/Mm."),
    ("theta_J", "Current-weighted angle between J and B in degrees."),
    ("sigma_J", "Current-weighted sine of the J-B angle."),
    ("CWsin", "Alias for sigma_J used in NLFF comparisons."),
    ("mean_force_free_residual", "Mean |J x B| / |B|."),
    ("rms_force_free_residual", "Root-mean-square |J x B| / |B|."),
    ("E_tot", "Total magnetic energy."),
    ("E_free", "Free magnetic energy. Cartesian uses the FFT potential-field reference."),
    ("E_pot", "Potential magnetic energy estimate E_tot - E_free."),
    ("E_free_over_E_tot", "Free-energy fraction."),
    ("mean_B", "Mean magnetic-field strength."),
    ("max_B", "Maximum magnetic-field strength."),
]
