"""Structured reference data used by the NF2 documentation."""

from nf2.evaluation.output_metrics import OUTPUT_METRICS

CONFIG_OPTIONS = [
    ("path", "str", "./runs/nf2", "Directory for checkpoints, logs, and extrapolation_result.nf2."),
    ("work_path", "str | null", "path/work", "Optional scratch directory for preprocessed arrays."),
    ("logging", "dict", "{}", "Options passed to the Lightning/W&B logger."),
    ("data.geometry", "cartesian | spherical", "required", "Extrapolation geometry."),
    ("data.normalization.Mm_per_ds", "float", "100", "Length represented by one model coordinate unit."),
    ("data.normalization.Gauss_per_dB", "float", "1000", "Magnetic-field strength represented by one model field unit."),
    ("data.boundaries", "list[dict]", "required", "Boundary observations, analytical fields, or maps."),
    ("data.boundaries[].Mm_per_pixel", "float", "dataset default", "Spatial sampling for this boundary in Mm per pixel."),
    ("data.boundaries[].coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate assigned to the boundary center, in Mm."),
    ("data.validation", "list[dict]", "geometry default", "Validation grids and plotting datasets."),
    ("data.sampler", "dict", "height sampler", "Cartesian physics sampling dataset."),
    ("data.samplers", "list[dict]", "random_radial_grouped", "Spherical physics sampling datasets."),
    ("data.potential_boundary", "dict", "FFT potential", "Cartesian potential boundary data. Use type: none to disable."),
    ("data.z_range", "list[float]", "loader default", "Cartesian height range in Mm where supported by the loader."),
    ("data.max_radius", "float", "loader default", "Spherical outer radius in solar radii where supported by the loader."),
    ("data.iterations", "int", "loader default", "Number of random sampler batches per epoch-like pass."),
    ("data.num_workers", "int", "4", "Default PyTorch DataLoader workers for training and validation loaders. Series preloading uses this value unless data.data_module_workers is set."),
    ("data.train_num_workers", "int", "data.num_workers", "PyTorch DataLoader workers for training loaders."),
    ("data.validation_num_workers", "int", "data.num_workers", "PyTorch DataLoader workers for validation loaders."),
    ("data.prefetch_factor", "int", "5", "Training DataLoader prefetch factor when workers are enabled."),
    ("data.persistent_workers", "bool", "true", "Keep training DataLoader workers alive while a loader is active."),
    ("data.preload_data_modules", "bool", "true", "For series runs, preload all step data modules up front instead of loading each step lazily."),
    ("data.data_module_workers", "int", "data.num_workers", "Series-only multiprocessing workers used to preload per-step data modules."),
    ("model.field", "vector_potential | b", "vector_potential", "Field representation."),
    ("model.network.type", "siren", "siren", "Only SIREN networks are supported."),
    ("model.network.hidden_dim", "int", "256 cartesian, 512 spherical", "SIREN hidden width."),
    ("model.network.layers", "int", "model default", "Number of SIREN layers."),
    ("model.network.w0", "float", "model default", "SIREN frequency scale for hidden layers."),
    ("model.network.w0_initial", "float", "model default", "SIREN frequency scale for the first layer."),
    ("training.epochs", "int", "10", "Number of Lightning epochs."),
    ("training.optimizer.start", "float", "5e-4", "Initial learning rate."),
    ("training.optimizer.end", "float", "5e-5", "Final learning rate."),
    ("training.optimizer.iterations", "int", "100000", "Learning-rate schedule length."),
    ("training.reload_dataloaders_every_n_epochs", "int", "1 for series", "Series cadence for advancing to the next dataset."),
    ("training.check_val_every_n_epoch", "int", "1", "Lightning validation cadence. Series examples use 10 to validate every 10th dataset."),
    ("training.trainer", "dict", "{}", "Additional Lightning Trainer keyword arguments."),
    ("losses[].type", "str", "geometry default", "Loss implementation name."),
    ("losses[].name", "str", "type", "Stable logging and scaling identifier."),
    ("losses[].weight", "float | schedule", "required when explicit", "Loss weight. The legacy lambda key is not accepted."),
    ("losses[].datasets", "str | list[str]", "loss default", "Dataset ids used by the loss."),
    ("loss_scaling", "list[dict]", "geometry default", "Spatial scaling modules for selected losses."),
    ("callbacks", "list[dict]", "geometry default", "Validation plots and metrics logged during training."),
    ("callbacks[].plot", "bool", "true", "For plotting callbacks, set false to keep scalar metrics but skip image rendering/logging."),
    ("transforms", "list[dict]", "[]", "Optional coordinate/field transforms applied to datasets."),
    ("meta_path", "str", "none", "Optional previous NF2 state used by series runs."),
]


DATASET_TYPES = [
    ("analytical", "benchmark boundary", "Low & Lou analytical fields for case1/case2 benchmarks."),
    ("sharp", "cartesian boundary", "SHARP CEA Br/Bt/Bp FITS input, optionally with uncertainty maps."),
    ("fits", "cartesian boundary", "Generic Cartesian Br/Bt/Bp FITS files."),
    ("los_trv_azi", "cartesian boundary", "LOS/transverse/azimuth FITS input with automatic disambiguation support."),
    ("los", "cartesian boundary", "Line-of-sight-only Cartesian boundary input."),
    ("fld_inc_azi", "cartesian boundary", "Field strength/inclination/azimuth FITS input."),
    ("height", "cartesian sampler", "Random Cartesian volume samples for force-free and potential losses."),
    ("potential", "cartesian boundary", "Potential-field boundary generated from the photospheric boundary."),
    ("map", "spherical boundary", "Spherical Br/Bt/Bp map input for full-disk or synoptic maps."),
    ("random_radial_grouped", "spherical sampler", "Grouped radial samples in the spherical volume."),
    ("sphere", "spherical validation", "Spherical validation grid for field-quality callbacks."),
    ("spherical_slices", "spherical validation", "Radial or angular slices for spherical visualization callbacks."),
]

DATASET_KEYS = [
    (
        "analytical",
        "benchmark boundary",
        [
            ("case", "int | str", "1", "Analytical Low & Lou case identifier."),
            ("bounds", "list[float]", "loader default", "Physical Cartesian volume bounds for the benchmark field."),
            ("resolution", "int | list[int]", "loader default", "Sampling resolution used to generate the benchmark boundary."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training batch."),
        ],
    ),
    (
        "sharp",
        "cartesian boundary or validation",
        [
            ("files.Br", "str", "required", "Radial magnetic-field FITS file."),
            ("files.Bt", "str", "required", "Theta/transverse magnetic-field FITS file."),
            ("files.Bp", "str", "required", "Phi/azimuthal magnetic-field FITS file."),
            ("errors.*", "str", "optional", "Optional uncertainty FITS files, stored as `error_path` internally."),
            ("Mm_per_pixel", "float", "FITS/WCS default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("slice", "slice | null", "null", "Optional image subset."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "fits",
        "cartesian boundary or validation",
        [
            ("files.Br", "str", "required", "Radial/vertical magnetic-field FITS file."),
            ("files.Bt", "str", "required", "Transverse x/theta component FITS file."),
            ("files.Bp", "str", "required", "Transverse y/phi component FITS file."),
            ("Mm_per_pixel", "float", "dataset default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "los_trv_azi",
        "cartesian boundary or validation",
        [
            ("files.B_los", "str", "required", "Line-of-sight magnetic-field FITS file."),
            ("files.B_trv", "str", "required", "Transverse-field magnitude FITS file."),
            ("files.B_azi", "str", "required", "Azimuth FITS file."),
            ("ambiguous_azimuth", "bool", "false", "Train/evaluate both azimuth disambiguation branches when supported by the loss."),
            ("load_map", "bool", "dataset default", "Load map metadata for coordinate conversion and plotting."),
            ("height_mapping", "dict", "none", "Map this boundary to a height or learned height range, for multi-height runs."),
            ("Mm_per_pixel", "float", "dataset default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "los",
        "cartesian boundary or validation",
        [
            ("files.B_los", "str", "required", "Line-of-sight magnetic-field FITS file."),
            ("Mm_per_pixel", "float", "dataset default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "fld_inc_azi",
        "cartesian boundary or validation",
        [
            ("files.B", "str", "required", "Field-strength FITS file."),
            ("files.inc", "str", "required", "Inclination FITS file."),
            ("files.azi", "str", "required", "Azimuth FITS file."),
            ("Mm_per_pixel", "float", "dataset default", "Boundary plate scale in Mm per pixel."),
            ("coordinate_center", "list[float] | dict", "[0, 0]", "Cartesian coordinate of the image center in Mm."),
            ("batch_size", "int", "shared boundary batch size", "Boundary samples per training or validation batch."),
        ],
    ),
    (
        "height",
        "cartesian sampler",
        [
            ("batch_size", "int", "16384 in examples", "Random volume samples per training batch."),
            ("z_sample", "int", "128", "Number of heights sampled per xy location."),
            ("z_sampling_exponent", "float", "2", "Bias random samples toward lower heights when greater than 1."),
            ("length", "int | null", "data.iterations", "Number of sampler batches per epoch-like pass."),
            ("requires_jacobian", "bool", "true", "Required for force-free, divergence, and potential losses."),
        ],
    ),
    (
        "potential",
        "cartesian potential boundary",
        [
            ("type", "potential | potential_top | none", "potential", "Potential-field side/top boundary mode."),
            ("strides", "int", "4", "Downsample factor for generating the potential boundary."),
            ("method", "fft | direct", "fft", "Potential-field solver."),
            ("batch_size", "int", "boundary batch size / 4", "Potential boundary samples per batch."),
            ("requires_jacobian", "bool", "false", "Usually disabled for boundary matching."),
        ],
    ),
    (
        "cube",
        "cartesian validation",
        [
            ("ds_per_pixel", "float", "1 / validation_pixel_per_ds", "Validation grid spacing in model units."),
            ("batch_size", "int", "validation_batch_size", "Validation samples per batch."),
            ("requires_jacobian", "bool", "true", "Needed for quality metrics that use derivatives."),
        ],
    ),
    (
        "slices",
        "cartesian validation",
        [
            ("n_slices", "int", "10", "Number of height slices to evaluate and plot."),
            ("batch_size", "int", "4096", "Validation samples per batch."),
            ("requires_jacobian", "bool", "true", "Needed for current-density plots."),
        ],
    ),
    (
        "map",
        "spherical boundary or validation",
        [
            ("files.Br", "str", "required", "Radial magnetic-field map."),
            ("files.Bt", "str", "required", "Theta magnetic-field map."),
            ("files.Bp", "str", "required", "Phi magnetic-field map."),
            ("errors.Br_err", "str", "optional", "Radial uncertainty map, merged into the file map internally."),
            ("errors.Bt_err", "str", "optional", "Theta uncertainty map, merged into the file map internally."),
            ("errors.Bp_err", "str", "optional", "Phi uncertainty map, merged into the file map internally."),
            ("mask_configs", "dict", "optional", "Optional masking/filtering, for example a `mu_filter`."),
            ("batch_size", "int", "data.batch_size or dataset default", "Map samples per batch."),
            ("requires_jacobian", "bool", "false for boundary examples", "Enable only when the dataset feeds derivative-based losses."),
        ],
    ),
    (
        "random_radial_grouped",
        "spherical sampler",
        [
            ("batch_size", "int", "16384 in examples", "Random spherical volume samples per batch."),
            ("n_lat_lon_sample", "int", "128", "Number of angular samples; `batch_size` must be divisible by this value."),
            ("radial_sampling_exponent", "float", "1", "Bias radial samples when greater than 1."),
            ("latitude_range", "list[float]", "[-90, 90]", "Latitude range in degrees unless `unit` is changed."),
            ("longitude_range", "list[float]", "[0, 360]", "Longitude range in degrees unless `unit` is changed."),
            ("length", "int | null", "data.iterations", "Internal sampler length; public YAML should usually use data.iterations."),
            ("requires_jacobian", "bool", "true", "Required for force-free, potential, and energy-gradient losses."),
        ],
    ),
    (
        "sphere",
        "spherical validation",
        [
            ("resolution", "int", "256", "Radial and longitude resolution of the validation sphere."),
            ("batch_size", "int", "1024", "Validation samples per batch."),
            ("latitude_range", "list[float]", "[-90, 90]", "Latitude range in degrees unless `unit` is changed."),
            ("longitude_range", "list[float]", "[0, 360]", "Longitude range in degrees unless `unit` is changed."),
            ("requires_jacobian", "bool", "true", "Needed for derivative-based quality metrics."),
        ],
    ),
    (
        "spherical_slices",
        "spherical validation",
        [
            ("longitude_resolution", "int", "256", "Longitude resolution for slice plots."),
            ("n_slices", "int", "5", "Number of radial slices."),
            ("batch_size", "int", "1024", "Validation samples per batch."),
            ("latitude_range", "list[float]", "[-90, 90]", "Latitude range in degrees unless `unit` is changed."),
            ("longitude_range", "list[float]", "[0, 360]", "Longitude range in degrees unless `unit` is changed."),
            ("requires_jacobian", "bool", "true", "Needed for current-density plots."),
        ],
    ),
]


CLI_COMMANDS = [
    (
        "nf2-extrapolate",
        "Run one YAML-configured extrapolation.",
        [
            ("--config", "required", "Path to a YAML configuration file."),
            ("--<placeholder>", "optional", "Any command-line option matching a <<placeholder>> in the YAML fills that value."),
        ],
    ),
    (
        "nf2-extrapolate-series",
        "Run a YAML-configured time series.",
        [
            ("--config", "required", "Path to a series YAML configuration file."),
            ("--reload", "false", "Rebuild work_path/data_module.pkl instead of reusing the saved series data module state."),
            ("--<placeholder>", "optional", "Fills matching <<placeholder>> values, including glob patterns for series files."),
        ],
    ),
    (
        "nf2-download",
        "Download supported JSOC/HMI data sources.",
        [
            ("--source", "hmi_sharp", "One of hmi_sharp, hmi_synoptic, hmi_full_disk."),
            ("--download_dir", "required", "Output directory."),
            ("--email", "required", "JSOC export email address."),
            ("--sharp_num", "none", "HARP/SHARP number for hmi_sharp."),
            ("--noaa_num", "none", "NOAA active-region number, resolved to HARP when needed."),
            ("--t_start", "source dependent", "Start time for hmi_sharp, hmi_full_disk, or Carrington-rotation lookup for hmi_synoptic."),
            ("--t_end", "none", "Optional end time; for hmi_synoptic this resolves an inclusive rotation range."),
            ("--cadence", "720s", "Cadence for time-range downloads."),
            ("--series", "source default", "JSOC series override."),
            ("--segments", "source default", "Comma-separated JSOC segments."),
            ("--carrington_rotation", "none", "Carrington rotation for hmi_synoptic; alternatively provide --t_start."),
            ("--carrington_rotation_end", "same as start", "Optional inclusive final Carrington rotation."),
            ("--synoptic_product", "vector", "One of vector, mr_polfil, both for hmi_synoptic."),
            ("--include_mr_polfil", "false", "Also download hmi.synoptic_mr_polfil_720s Mr_polfil for synoptic-map runs."),
            ("--no_convert_ptr", "false", "Disable HmiB2ptr conversion for full-disk vector data."),
            ("--keep_coordinates", "false", "Keep generated latitude/longitude files after full-disk conversion."),
        ],
    ),
    (
        "nf2-export",
        "Export NF2 results to exchange formats.",
        [
            ("nf2_path", "required", "One or more .nf2 paths or glob patterns."),
            ("--format", "vtk", "One of vtk, npz, hdf5, h5, fits, height, height-npz, height_npz."),
            ("--out", "none", "Output file for a single input."),
            ("--out-dir", "current directory", "Output directory for multiple inputs."),
            ("--Mm_per_pixel", "checkpoint default", "Cartesian export sampling."),
            ("--height_range", "full height", "Cartesian height range in Mm."),
            ("--x_range", "full x", "Cartesian x range in Mm."),
            ("--y_range", "full y", "Cartesian y range in Mm."),
            ("--radius_range", "0.999 1.3", "Spherical VTK radius range in solar radii."),
            ("--latitude_range", "-90 90", "Spherical VTK latitude range in degrees."),
            ("--longitude_range", "0 360", "Spherical VTK longitude range in degrees."),
            ("--pixels_per_solRad", "64", "Spherical VTK sampling resolution."),
            ("--metrics", "j", "Derived quantities to include."),
            ("--overwrite", "false", "Replace existing series export files."),
        ],
    ),
    (
        "nf2-metrics",
        "Print standard NLFF quality metrics.",
        [
            ("nf2_path", "required", "Path to extrapolation_result.nf2."),
            ("--device", "auto", "PyTorch evaluation device."),
            ("--progress", "false", "Show evaluation progress."),
            ("--batch_size", "output default", "Evaluation batch size."),
            ("--Mm_per_pixel", "checkpoint default", "Cartesian sampling."),
            ("--height_range", "full height", "Cartesian height range in Mm."),
            ("--x_range", "full x", "Cartesian x range in Mm."),
            ("--y_range", "full y", "Cartesian y range in Mm."),
            ("--spherical_sampling", "32 64 128", "Spherical radial, latitude, longitude sample counts."),
            ("--radius_range", "checkpoint range", "Spherical radius range in solar radii."),
            ("--latitude_range", "-90 90", "Spherical latitude range in degrees."),
            ("--longitude_range", "0 360", "Spherical longitude range in degrees."),
        ],
    ),
    (
        "nf2-noaa-to-sharp",
        "Resolve NOAA active-region numbers to SHARP/HARP numbers through JSOC metadata.",
        [
            ("--time", "required", "Observation time used for the NOAA-to-HARP lookup."),
            ("--email", "required", "JSOC export email address."),
            ("--noaa_nums", "all active regions", "One or more NOAA active-region numbers to resolve."),
        ],
    ),
]


EXPORT_METRICS = [
    (metric.name, ", ".join(metric.outputs), metric.description)
    for metric in OUTPUT_METRICS.values()
]


QUALITY_METRICS = [
    ("mean_abs_divB", "Mean absolute divergence in G/Mm."),
    ("rms_divB", "Root-mean-square divergence in G/Mm."),
    ("mean_abs_divB_over_B", "Mean |div B| / |B| in 1/Mm."),
    ("rms_divB_over_B", "Root-mean-square |div B| / |B| in 1/Mm."),
    ("theta_J", "Current-weighted angle between J and B in degrees."),
    ("sigma_J", "Current-weighted sine of the J-B angle."),
    ("CWsin", "Alias for sigma_J used in NLFF comparisons."),
    ("mean_force_free_residual", "Mean |J x B| / |B|."),
    ("rms_force_free_residual", "Root-mean-square |J x B| / |B|."),
    ("E_tot", "Total magnetic energy."),
    ("E_free", "Free magnetic energy. Cartesian uses the FFT potential-field reference."),
    ("E_pot", "Potential magnetic energy estimate E_tot - E_free."),
    ("E_free_over_E_tot", "Free-energy fraction."),
    ("mean_B", "Mean magnetic-field strength."),
    ("max_B", "Maximum magnetic-field strength."),
]
