---
path: "<<run_path>>"
work_path: "<<work_path>>"
logging:
  project: nf2
  name: "Cartesian multi-height"
data:
  geometry: cartesian
  normalization:
    Mm_per_ds: 100
    Gauss_per_dB: 1000
  boundaries:
    - id: photosphere
      type: los_trv_azi
      Mm_per_pixel: 0.09
      files:
        B_los: "<<photosphere_B_los>>"
        B_trv: "<<photosphere_B_trv>>"
        B_azi: "<<photosphere_B_azi>>"
      ambiguous_azimuth: true
      load_map: false
    - id: chromosphere
      type: los_trv_azi
      Mm_per_pixel: 0.09
      files:
        B_los: "<<chromosphere_B_los>>"
        B_trv: "<<chromosphere_B_trv>>"
        B_azi: "<<chromosphere_B_azi>>"
      height_mapping: { z: 2.0, z_min: 0.0, z_max: 20.0 }
      ambiguous_azimuth: true
      load_map: false
  sampler:
    type: height
    batch_size: 16384
  potential_boundary:
    id: potential
    type: potential
    strides: 4
  validation:
    - id: photosphere
      type: los_trv_azi
      Mm_per_pixel: 0.09
      files:
        B_los: "<<photosphere_B_los>>"
        B_trv: "<<photosphere_B_trv>>"
        B_azi: "<<photosphere_B_azi>>"
      ambiguous_azimuth: true
      load_map: false
    - id: chromosphere
      type: los_trv_azi
      Mm_per_pixel: 0.09
      files:
        B_los: "<<chromosphere_B_los>>"
        B_trv: "<<chromosphere_B_trv>>"
        B_azi: "<<chromosphere_B_azi>>"
      height_mapping: { z: 2.0, z_min: 0.0, z_max: 20.0 }
      ambiguous_azimuth: true
      load_map: false
    - id: cube
      type: cube
    - id: slices
      type: slices
  iterations: 10000
  z_range: [0, 100]
training:
  epochs: 30
losses:
  - type: boundary_los_trv_azi
    name: boundary
    weight: 1.0
    datasets: [photosphere, chromosphere]
    ambiguous: true
  - type: boundary
    name: potential_boundary
    weight: 10.0
    datasets: potential
  - type: force_free
    name: force_free
    weight: 1.0e-4
    datasets: [random]
  - type: potential
    name: potential
    weight: { type: step, steps: 5000, start: 1.0e-4, end: 0.0 }
    datasets: [random]
  - type: height
    name: height
    weight: 1.0e-5
    datasets: [chromosphere]
transforms:
  - type: height
    height_range: [0, 20]
    datasets: [chromosphere]
callbacks:
  - type: los_trv_azi_boundary
    dataset: photosphere
  - type: los_trv_azi_boundary
    dataset: chromosphere
  - type: metrics
    dataset: cube
  - type: slices
    dataset: slices
