run:
  mode: single
  geometry: cartesian
  output_dir: /glade/work/rjarolim/nf2/magnetostatic/cutoff_v01
  work_dir: /glade/derecho/scratch/rjarolim/nf2/cutoff_v01
logging:
  project: magnetostatic
  name: Cut-off
data:
  parameters:
    z_range:
    - 0
    - 60
    iterations: 10000
    batch_size: 8192
    random_batch_size: 16384
  train:
  - type: muram_cube
    name: bottom_b
    data_path: /glade/campaign/hao/radmhd/Rempel/Spot_Motion/case_B/3D
    iteration: 474000
    tau: 0.1
    batch_size: 4096
  validation: []
model:
  type: magneto_static
  dim: 256
  p_model_config:
    cutoff: true
    encoding_config:
      type: gaussian
training:
  epochs: 20
losses:
- type: boundary
  name: boundary
  lambda: 1.0
  ds_id:
  - bottom_b
  - potential
  b_scaling: true
- type: magneto_static
  lambda: 0.0001
- type: divergence
  lambda: 0.01
  b_scaling: true
- type: force_free
  lambda: 0.0
  b_scaling: true
- type: b_height_scaling
  lambda: 0.01
- type: p_height_scaling
  lambda: 0.01
