---
base_path: "/glade/work/rjarolim/nf2/magnetostatic/muram_X_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/muram_X_v01"
logging:
  project: magnetostatic
  name: muram magnetostatic - X
data:
  type: muram
  slices:
    - type: "3D"
      name: "photosphere_b"
      data_path: "/glade/campaign/hao/radmhd/rjarolim/magnetostatic"
      iteration: 1000000
      base_height: 116
      batch_size: 4096
    - type: 'pressure'
      name: 'pressure'
      data_path: "/glade/campaign/hao/radmhd/rjarolim/magnetostatic"
      iteration: 1000000
      base_height: 116
      batch_size: 4096
  random_config: {batch_size: 16384}
  num_workers: 8
  iterations: 10000
model:
  type: magneto_static
  p_profile_model_path: "/glade/work/rjarolim/nf2/magnetostatic/profile/log_p_model.pt"
  dim: 256
  encoding_config: {type: "gaussian", scale: 1}
  vector_potential: False
training:
  epochs: 100
  loss_config:
    - type: boundary
      name: boundary
      lambda: 1.0
      ds_id: [photosphere_b, potential]
      height_scaling: True
    - type: pressure_boundary
      name: pressure_boundary
      lambda: 0.0 #1.0
      ds_id: [pressure]
      height_scaling: True
    - type: magneto_static
      lambda: 1.0e-2
    - type: divergence
      lambda: 1.0e-2
      height_scaling: True
    - type: pressure_profile
      lambda: 0.0
    - type: b_height_scaling
      lambda: 1.0e-2