---
base_path: "/glade/work/rjarolim/nf2/magnetostatic/muram_FR_FF_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/muram_FR_FF_v01"
logging:
  project: magnetostatic
  name: muram magnetostatic - FR - force-free
data:
  type: muram
  slices:
    - type: "cube"
      name: "photosphere_b"
      data_path: "/glade/campaign/hao/radmhd/Rempel/Spot_Motion/case_B/3D"
      iteration: 474000
      base_height: 64
      batch_size: 4096
  max_height: 60
  random_config: {batch_size: 8192}
  num_workers: 8
  iterations: 10000
model:
  type: b_scaled
  dim: 256
  encoding_config: {type: "gaussian", scale: 2}
training:
  epochs: 20
  loss_config:
    - type: boundary
      name: boundary
      lambda: 1.0
      ds_id: [photosphere_b, potential]
      height_scaling: True
    - type: force_free
      lambda: 1.0e-2
      height_scaling: True
    - type: divergence
      lambda: 1.0e-2
      height_scaling: True
    - type: b_height_scaling
      lambda: 1.0e-2