---
base_path: "/glade/work/rjarolim/nf2/magnteostatic/muram_implicit_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/muram_implicit_v01"
logging:
  project: magnetostatic
  name: muram implicit
data:
  type: muram
  slices:
    - type: "3D"
      name: "photosphere_b"
      data_path: "/glade/campaign/hao/radmhd/rjarolim/magnetostatic"
      iteration: 1000000
      base_height: 116
      batch_size: 4096
  random_config: {batch_size: 16384}
  num_workers: 8
  iterations: 10000
model:
  type: b_scaled
  dim: 256
  encoding_config: {type: "gaussian", scale: 1}
training:
  epochs: 100
  loss_config:
    - type: boundary
      name: boundary
      lambda: 1.0
      ds_id: [photosphere_b, potential]
      height_scaling: True
    - type: implicit_magnetostatic
      lambda: 1.0e-4
      height_scaling: True
    - type: divergence
      lambda: 1.0e-2
      height_scaling: True
