---
base_path: "/glade/work/rjarolim/nf2/magnteostatic/muram_ff_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/muram_ff_v01"
logging:
  project: magnteostatic
  name: muram force-free
data:
  type: muram
  slices:
    - type: "3D"
      data_path: "/glade/campaign/hao/radmhd/rjarolim/magnetostatic"
      iteration: 1000000
      base_height: 116
      batch_size: 4096
  num_workers: 8
  iterations: 10000
model:
  type: b
  dim: 128
training:
  epochs: 100
  loss_config:
    - type: boundary
      name: boundary
      lambda: 1.0
      ds_id: [boundary_01, potential]
    - type: force_free
      lambda: 1.0e-2
    - type: divergence
      lambda: 1.0e-2
