---
base_path: "/glade/work/rjarolim/nf2/magnetostatic/transfer_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/transfer_v01"
logging:
  project: magnetostatic
  name: Transfer
data:
  type: cartesian
  slices:
    - type: "muram_cube"
      data_path: "/glade/campaign/hao/radmhd/Rempel/Spot_Motion/case_B/3D"
      iteration: 474000
      tau: 0.1
      batch_size: 4096
  z_range: [0, 60]
  iterations: 10000
  batch_size: 8192
  random_batch_size: 16384
model:
  type: magneto_static
  b_model_config: {path: "/glade/work/rjarolim/nf2/magnetostatic/force_free_v03/extrapolation_result.nf2", freeze: true}
  dim: 256
training:
  epochs: 20
  loss_config:
    - type: boundary
      name: boundary
      lambda: {start: 1.0e+3, end: 1.0, iterations: 5.0e+4}
      ds_id: boundary_01
    - type: boundary
      name: potential
      lambda: 10.0
      ds_id: potential
    - type: divergence
      lambda: 1.0e-2
    - type: magneto_static
      lambda: 1.0e-2
    - type: force_free
      lambda: 0.0