---
base_path: "/glade/work/rjarolim/nf2/scaling/muram_mfr_b_scaling_encoding_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/muram_mfr_b_scaling_encoding_v01"
logging:
  project: scaling
  name: B Scaling Encoding
data:
  type: cartesian
  slices:
    - type: "muram_slice"
      data_path: "/glade/campaign/hao/radmhd/Rempel/Spot_Motion/case_B/2D/tau_slice_1.000.474000"
      los_trv_azi_transform: True
  num_workers: 8
  iterations: 10000
  batch_size: 8192
  random_batch_size: 16384
  z_range: [0, 60]
model:
  type: b_scaled
  dim: 256
  encoding_config: {type: 'gaussian'}
training:
  epochs: 15
  loss_config:
    - type: boundary_los_trv_azi
      name: boundary
      lambda: 1.0
      ds_id: boundary_01
      b_scaling: True
    - type: boundary
      name: potential_boundary
      lambda: 1.0
      ds_id: potential
      b_scaling: True
    - type: force_free
      lambda: 1.0e-3
      b_scaling: True
    - type: divergence
      lambda: 1.0e-3
      b_scaling: True
    - type: b_height_scaling
      lambda: 1.0e-2
