---
base_path: "/glade/work/rjarolim/nf2/scaling/muram_mfr_height_scaling_v02"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/muram_mfr_height_scaling_v02"
logging:
  project: scaling
  name: Height Scaling
data:
  type: cartesian
  slices:
    - type: "muram_slice"
      data_path: "/glade/campaign/hao/radmhd/Rempel/Spot_Motion/case_B/2D/tau_slice_1.000.474000"
      los_trv_azi_transform: True
  num_workers: 8
  iterations: 10000
  batch_size: 8192
  random_batch_size: 16384
  z_range: [0, 60]
model:
  type: b
  dim: 256
training:
  epochs: 15
  loss_config:
    - type: boundary_los_trv_azi
      name: boundary
      lambda: 1.0
      ds_id: boundary_01
    - type: boundary
      name: potential_boundary
      lambda: 1.0e-1
      ds_id: potential
      height_scaling: True
    - type: force_free
      lambda: 1.0e-3
      height_scaling: True
    - type: divergence
      lambda: 1.0e-3
      height_scaling: True
