---
path: "<<run_path>>"
work_path: "<<work_path>>"
meta_path: "<<meta_path>>"
logging:
  project: nf2
  name: "Cartesian SHARP CEA series"
data:
  geometry: cartesian
  normalization:
    Mm_per_ds: 100
    Gauss_per_dB: 1000
  boundaries:
    - id: boundary
      type: sharp
      files:
        Br: "<<Br_pattern>>"
        Bt: "<<Bt_pattern>>"
        Bp: "<<Bp_pattern>>"
      errors:
        Br_err: "<<Br_err_pattern>>"
        Bt_err: "<<Bt_err_pattern>>"
        Bp_err: "<<Bp_err_pattern>>"
      slice: null
  sampler:
    type: height
    batch_size: 16384
  potential_boundary:
    id: potential
    type: potential
    strides: 4
  iterations: 2000
  z_range: [0, 80]
training:
  reload_dataloaders_every_n_epochs: 1
  check_val_every_n_epoch: 10
losses:
  - type: boundary
    name: boundary
    weight: 1.0
    datasets: [boundary]
  - type: boundary
    name: potential_boundary
    weight: 10.0
    datasets: potential
  - type: force_free
    name: force_free
    weight: 1.0e-3
    datasets: [random]
  - type: potential
    name: potential
    weight: 0.0
    datasets: [random]
loss_scaling:
  - type: b_height
    name: b_height
    loss_ids: [force_free, potential]
callbacks:
  - type: boundary
    dataset: boundary
  - type: metrics
    dataset: cube
  - type: slices
    dataset: slices
