run:
  mode: single
  geometry: cartesian
  output_dir: /glade/work/rjarolim/nf2/topology/muram_sma_1slices_ambiguous_v01
  work_dir: /glade/derecho/scratch/rjarolim/nf2/muram_sma_1slices_ambiguous_v01
logging:
  project: topology
  name: MURAM SMA - tau1 - ambiguous
data:
  parameters:
    random_config:
      type: height
    num_workers: 16
    iterations: 10000
    z_range:
    - 0
    - 50
  train:
  - type: muram_slice
    ds_id: tau_1.0
    data_path: /glade/campaign/hao/radmhd/Rempel/Spot_Motion/case_A/2D/tau_slice_1.000.399000
    los_trv_azi_transform: true
    ambiguous_azimuth: true
  validation: []
model:
  type: vector_potential
  dim: 256
  encoding_config:
    type: gaussian
training:
  epochs: 30
losses:
- type: boundary_los_trv_azi
  name: boundary
  lambda: 1.0
  ds_id: tau_1.0
  ambiguous: true
- type: boundary
  name: potential_boundary
  lambda: 10.0
  ds_id: potential
- type: force_free
  name: force_free
  lambda: 0.0001
  ds_id:
  - random
- type: potential
  name: potential
  lambda:
    type: step
    steps: 5000.0
    start: 1.0e-05
    end: 0.0
  ds_id:
  - random
callbacks:
- type: los_trv_azi_boundary
  name: boundary-tau_1.0
  ds_id: tau_1.0
- type: metrics
  name: metrics-tau_1.0
  ds_id: cube
- type: slices
  ds_id: slices
loss_scaling:
- type: b_height
  name: b_height
  loss_ids:
  - force_free
  - potential
