---
base_path: "/glade/work/rjarolim/nf2/sst/13392_1slice_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/13392_1slice_v01"
logging:
  project: nf2-sst
  name: "13392 SST - 6173"
data:
  type: fits
  slices:
    - type: los_trv_azi
      Mm_per_pixel: 0.09
      fits_path:
        B_los: "/glade/work/rjarolim/data/SST/campaign_2023/BLOS_panorama0851_6173_StkIQUV_rebin.fits"
        B_trv: "/glade/work/rjarolim/data/SST/campaign_2023/BTRV_panorama0851_6173_StkIQUV_rebin.fits"
        B_azi: "/glade/work/rjarolim/data/SST/campaign_2023/BAZI_panorama0851_6173_StkIQUV_rebin.fits"
      mask_path: "/glade/work/rjarolim/data/SST/campaign_2023/mask.fits"
      load_map: False
      batch_size: 8192
  num_workers: 8
  iterations: 10000
model:
  type: vector_potential
  dim: 256
training:
  epochs: 20
  loss_config:
    - type: boundary_los_trv_azi
      lambda: 1.0
      ds_id: [boundary_01]
    - type: boundary
      name: potential_boundary
      lambda: 0.1
      ds_id: potential
    - type: force_free
      lambda: 1.0e-2
    - type: divergence
      lambda:  0.0
    - type: azimuth_disambiguation
      lambda: {start: 1.0, end: 1.0e-2, iterations: 5.0e+4}
      ds_id: [ boundary_01 ]
  check_val_every_n_epoch: 1
  transforms:
    - type: azimuth
      ds_id: [ boundary_01, validation_boundary_01 ]
callbacks:
  - type: disambiguation
    ds_id: validation_boundary_01
