---
base_path: "/glade/work/rjarolim/nf2/sst/sharp_13392_disamb_v01"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/sharp_13392_disamb_v01"
logging:
  project: nf2-sst
  name: "13392 SHARP DISAMB"
data:
  type: fits
  slices:
    - type: fld_inc_azi
      Mm_per_pixel: 0.09
      fits_path:
        B_fld: "/glade/work/rjarolim/data/nf2/13392/hmi.sharp_720s.9875.20230806_091200_TAI.field.fits"
        B_inc: "/glade/work/rjarolim/data/nf2/13392/hmi.sharp_720s.9875.20230806_091200_TAI.inclination.fits"
        B_azi: "/glade/work/rjarolim/data/nf2/13392/hmi.sharp_720s.9875.20230806_091200_TAI.azimuth.fits"
#        B_amb: "/glade/work/rjarolim/data/nf2/13392/hmi.sharp_720s.9875.20230806_091200_TAI.disambig.fits"
      batch_size: 8192
  num_workers: 8
  iterations: 10000
model:
  type: vector_potential
  dim: 256
training:
  epochs: 100
  loss_config:
    - type: boundary_los_trv_azi
      name: boundary_los_trv_azi
      disambiguate: False
      lambda: 1.0
      ds_id: [boundary_01]
    - type: boundary
      name: potential_boundary
      lambda: 0.1
      ds_id: potential
    - type: force_free
      lambda: 1.0e-2
    - type: divergence
      lambda:  0.0
  check_val_every_n_epoch: 1
