---
base_path: "/glade/work/rjarolim/nf2/disambiguation/muram_mfr_ambiguous_v02"
work_directory: "/glade/derecho/scratch/rjarolim/nf2/muram_mfr_ambiguous_v02"
logging:
  project: auto-disambiguation
  name: MURAM MFR - ambiguous
data:
  type: muram
  slices:
    - data_path: "/glade/campaign/hao/radmhd/Rempel/Spot_Motion/case_B/2D/tau_slice_1.000.474000"
      los_trv_azi_transform: True
      batch_size: 4096
    - data_path: "/glade/campaign/hao/radmhd/Rempel/Spot_Motion/case_B/2D/tau_slice_0.000001.474000"
      height_mapping: { z: 2.0, z_min: 0, z_max: 23 }
      los_trv_azi_transform: True
      batch_size: 4096
  num_workers: 8
  iterations: 1000
model:
  type: vector_potential
  dim: 256
training:
  epochs: 100
  loss_config:
    - type: boundary_los_trv_azi
      name: boundary_los_trv_azi
      disambiguate: True
      lambda: 1.0
      ds_id: [boundary_01, boundary_02]
    - type: boundary
      name: potential_boundary
      lambda: 0.1
      ds_id: potential
    - type: force_free
      lambda: 1.0e-2
    - type: divergence
      lambda:  0.0
    - type: height
      name: height
      lambda: 1.0e-3
      ds_id: [ boundary_02 ]
  coordinate_transform:
    type: height
    ds_id: [ boundary_02 ]
    validation_ds_id: [ validation_boundary_02 ]
  check_val_every_n_epoch: 1
