---
base_path: "/glade/work/rjarolim/nf2/hinode_v2/ar_10978_0_100_w01_forcedBz"
work_directory: "/glade/derecho/scratch/rjarolim/topology/ar_10978_0_100_w01_forcedBz"
logging:
  project: nf2
  name: "10978 Hinode 0.100 w0.1 - forced Bz"
data:
  type: cartesian
  train_configs:
    - type: numpy
      ds_id: hinode
      data_path: "/glade/work/rjarolim/data/nf2/ar_10978/bin02_BC.npz"
      Mm_per_pixel: 0.21182084
  valid_configs:
    - type: numpy
      ds_id: hinode
      data_path: "/glade/work/rjarolim/data/nf2/ar_10978/bin02_BC.npz"
      Mm_per_pixel: 0.21182084
    - type: cube
      ds_id: cube
    - type: slices
      ds_id: slices
  num_workers: 8
  iterations: 10000
  batch_size: 8192
  random_config:
    batch_size: 16384
  z_range: [ 0, 107 ]
  boundary_config:
    type: potential
    batch_size: 2048
    strides: 4
model:
  type: vector_potential
  dim: 256
training:
  epochs: 30

loss:
- type: boundary
  name: boundary
  lambda: {start: 1.0e+3, end: 1.0, iterations: 5.0e+4}
  ds_id: hinode
  weights: [0.1, 0.1, 100.0]
- type: boundary
  name: potential_boundary
  lambda: 1.0e+1
  ds_id: potential
- type: force_free
  lambda: 0.1

callbacks:
    # Boundary callbacks
  - type: boundary
    name: boundary
    ds_id: hinode
  # Cube evaluation
  - type: metrics
    name: metrics
    ds_id: cube
  - type: slices
    ds_id: slices