run:
  mode: single
  geometry: cartesian
  output_dir: /glade/work/rjarolim/nf2/nlte/sst_tau0_tau-5_v01
  work_dir: /glade/derecho/scratch/rjarolim/nf2/sst_tau0_tau-5_v01
logging:
  project: NLTE
  name: 'SST - NLTE - tau: 0,-5'
data:
  parameters:
    num_workers: 16
    iterations: 1000
    z_range:
    - 0
    - 50
  train:
  - type: los_trv_azi
    ds_id: ltau_-0.0
    Mm_per_pixel: 0.09
    fits_path:
      B_los: /glade/work/rjarolim/data/nf2/nlte/BLOS_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
      B_trv: /glade/work/rjarolim/data/nf2/nlte/BTRV_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
      B_azi: /glade/work/rjarolim/data/nf2/nlte/BAZIPRE_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
      Z: /glade/work/rjarolim/data/nf2/nlte/Z_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
    load_map: false
  - type: los_trv_azi
    ds_id: ltau_-5.0
    Mm_per_pixel: 0.09
    fits_path:
      B_los: /glade/work/rjarolim/data/nf2/nlte/BLOS_2018-09-30T09:22:00_NLTE_ltau_-5.0.fits
      B_trv: /glade/work/rjarolim/data/nf2/nlte/BTRV_2018-09-30T09:22:00_NLTE_ltau_-5.0.fits
      B_azi: /glade/work/rjarolim/data/nf2/nlte/BAZIPRE_2018-09-30T09:22:00_NLTE_ltau_-5.0.fits
      Z: /glade/work/rjarolim/data/nf2/nlte/Z_2018-09-30T09:22:00_NLTE_ltau_-5.0.fits
    mask_config:
      path: /glade/work/rjarolim/data/nf2/nlte/mask.fits
    load_map: false
  validation:
  - type: los_trv_azi
    ds_id: ltau_-0.0
    Mm_per_pixel: 0.09
    fits_path:
      B_los: /glade/work/rjarolim/data/nf2/nlte/BLOS_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
      B_trv: /glade/work/rjarolim/data/nf2/nlte/BTRV_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
      B_azi: /glade/work/rjarolim/data/nf2/nlte/BAZIPRE_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
      Z: /glade/work/rjarolim/data/nf2/nlte/Z_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
    load_map: false
  - type: los_trv_azi
    ds_id: ltau_-5.0
    Mm_per_pixel: 0.09
    fits_path:
      B_los: /glade/work/rjarolim/data/nf2/nlte/BLOS_2018-09-30T09:22:00_NLTE_ltau_-5.0.fits
      B_trv: /glade/work/rjarolim/data/nf2/nlte/BTRV_2018-09-30T09:22:00_NLTE_ltau_-5.0.fits
      B_azi: /glade/work/rjarolim/data/nf2/nlte/BAZIPRE_2018-09-30T09:22:00_NLTE_ltau_-5.0.fits
      Z: /glade/work/rjarolim/data/nf2/nlte/Z_2018-09-30T09:22:00_NLTE_ltau_-5.0.fits
    mask_config:
      path: /glade/work/rjarolim/data/nf2/nlte/mask.fits
    load_map: false
  - type: cube
    ds_id: cube
  - type: slices
    ds_id: slices
model:
  type: vector_potential
  dim: 256
training:
  epochs: 100
losses:
- type: boundary_los_trv_azi
  name: bottom
  lambda: 1.0
  ds_id:
  - ltau_-0.0
  ambiguous: true
- type: boundary_los_trv_azi
  name: internal
  lambda:
    start: 0.0001
    end: 1.0
    iterations: 10000
  ds_id:
  - ltau_-5.0
  ambiguous: true
- type: boundary
  name: potential_boundary
  lambda: 1.0
  ds_id: potential
- type: force_free
  name: force_free
  lambda: 0.001
- type: height
  name: height
  lambda: 0.01
  ds_id:
  - ltau_-5.0
callbacks:
- type: los_trv_azi_boundary
  name: boundary-0.0
  ds_id: ltau_-0.0
- type: los_trv_azi_boundary
  name: boundary-5.0
  ds_id: ltau_-5.0
- type: metrics
  name: metrics
  ds_id: cube
- type: slices
  ds_id: slices
transforms:
- type: nlte_height
  height_range:
  - 0
  - 5
  ds_id:
  - ltau_-5.0
loss_scaling:
- type: potential_fit
  name: potential_fit
  loss_ids:
  - bottom
  - internal
  - potential_boundary
  - force_free
  ref_file: /glade/work/rjarolim/data/nf2/nlte/BLOS_2018-09-30T09:22:00_NLTE_ltau_-0.0.fits
  Mm_per_pixel: 0.09
